# ----------------------------------------
# Created on: Sat Feb 25 20:39:54 2023
# Auto generated by Pango
# ----------------------------------------

vlib  work
vmap  work ./work
vmap  usim "D:/pango/PDS_2022.1/pango_sim_libraries/usim"
vmap  adc "D:/pango/PDS_2022.1/pango_sim_libraries/adc"
vmap  ddrc "D:/pango/PDS_2022.1/pango_sim_libraries/ddrc"
vmap  ddrphy "D:/pango/PDS_2022.1/pango_sim_libraries/ddrphy"
vmap  hsst_e2 "D:/pango/PDS_2022.1/pango_sim_libraries/hsst_e2"
vlog   "D:/FPGA/Project/I2S/source/i2s_top.v" -work work
vlog   "D:/FPGA/Project/I2S/source/dac_out.v" -work work
vlog   "D:/FPGA/Project/I2S/source/top.v" -work work
vlog   "D:/FPGA/Project/I2S/source/keyfilter.v" -work work
vlog   "D:/FPGA/Project/I2S/ipcore/dac_pll/dac_pll.v" -work work
vlog   "D:/FPGA/Project/I2S/source/sim_top.v" -work work

# ----------------------------------------
