# ----------------------------------------
# Created on: Sat Feb 25 20:39:54 2023
# Auto generated by Pango
# ----------------------------------------

vsim  -novopt  -L work -L usim -L adc -L ddrc -L ddrphy -L hsst_e2 sim_top usim.GTP_GRS
add wave *
view wave
view structure
view signals

run 1000ns

# ----------------------------------------
