
//
// Generated by Fabric Compiler (version 2022.1<build 99559>) at Sat Feb 25 17:56:20 2023
//
module top
(
    mic_out,
    mic_sck,
    mic_ws,
    clk50M,
    mic_sd,
    rst_n
);

(* PAP_IO_DIRECTION="INPUT", PAP_IO_LOC="B5", PAP_IO_VCCIO="3.3", PAP_IO_STANDARD="LVCMOS12", PAP_IO_NONE="TRUE", PAP_PORT_BUF_UNIT_TYPE="GTP_INBUF" *)    input clk50M;
(* PAP_IO_DIRECTION="INPUT", PAP_IO_LOC="R11", PAP_IO_VCCIO="3.3", PAP_IO_STANDARD="LVCMOS12", PAP_IO_NONE="TRUE", PAP_PORT_BUF_UNIT_TYPE="GTP_INBUF" *)    input mic_sd;
(* PAP_IO_DIRECTION="INPUT", PAP_IO_LOC="U12", PAP_IO_VCCIO="3.3", PAP_IO_STANDARD="LVCMOS12", PAP_IO_NONE="TRUE", PAP_PORT_BUF_UNIT_TYPE="GTP_INBUF" *)    input rst_n;
(* PAP_IO_DIRECTION="OUTPUT", PAP_IO_LOC="U10", PAP_IO_VCCIO="3.3", PAP_IO_STANDARD="LVCMOS33", PAP_IO_DRIVE="4", PAP_IO_NONE="TRUE", PAP_IO_SLEW="SLOW", PAP_PORT_BUF_UNIT_TYPE="GTP_OUTBUF" *)    output mic_out;
(* PAP_IO_DIRECTION="OUTPUT", PAP_IO_LOC="P11", PAP_IO_VCCIO="3.3", PAP_IO_STANDARD="LVCMOS33", PAP_IO_DRIVE="4", PAP_IO_NONE="TRUE", PAP_IO_SLEW="SLOW", PAP_PORT_BUF_UNIT_TYPE="GTP_OUTBUF" *)    output mic_sck;
(* PAP_IO_DIRECTION="OUTPUT", PAP_IO_LOC="P14", PAP_IO_VCCIO="3.3", PAP_IO_STANDARD="LVCMOS33", PAP_IO_DRIVE="4", PAP_IO_NONE="TRUE", PAP_IO_SLEW="SLOW", PAP_PORT_BUF_UNIT_TYPE="GTP_OUTBUF" *)    output mic_ws;

    wire \CLMA_98_125/ntCECO ;
    wire \CLMA_98_125/ntRSCO ;
    wire \CLMA_98_125/ntRS_P ;
    wire \CLMA_98_125/ntY0 ;
    wire \CLMA_98_132/ntCECO ;
    wire \CLMA_98_132/ntCYA ;
    wire \CLMA_98_132/ntCYB ;
    wire \CLMA_98_132/ntCYC ;
    wire \CLMA_98_132/ntRS_P ;
    wire \CLMA_98_132/ntY0 ;
    wire \CLMA_98_132/ntY1 ;
    wire \CLMA_98_132/ntY2 ;
    wire \CLMA_98_132/ntY3 ;
    wire \CLMA_98_136/ntCECO ;
    wire \CLMA_98_136/ntCYA ;
    wire \CLMA_98_136/ntCYB ;
    wire \CLMA_98_136/ntCYC ;
    wire \CLMA_98_136/ntY0 ;
    wire \CLMA_98_136/ntY1 ;
    wire \CLMA_98_136/ntY2 ;
    wire \CLMA_98_136/ntY3 ;
    wire \CLMA_98_140/ntCECO ;
    wire \CLMA_98_140/ntCYA ;
    wire \CLMA_98_140/ntCYB ;
    wire \CLMA_98_140/ntRSCO ;
    wire \CLMA_98_140/ntY0 ;
    wire \CLMA_98_140/ntY1 ;
    wire \CLMA_98_140/ntY2 ;
    wire \CLMA_102_128/ntCECO ;
    wire \CLMA_102_128/ntRS_P ;
    wire \CLMA_102_136/ntCECO ;
    wire \CLMA_102_136/ntRSCO ;
    wire \CLMA_106_121/ntCYA ;
    wire \CLMA_106_121/ntCYB ;
    wire \CLMA_106_121/ntCYC ;
    wire \CLMA_106_125/ntCYA ;
    wire \CLMA_106_125/ntCYB ;
    wire \CLMA_106_125/ntCYC ;
    wire \CLMA_106_128/ntCECO ;
    wire \CLMA_106_128/ntRSCO ;
    wire \CLMA_106_128/ntRS_P ;
    wire \CLMA_106_129/ntCECO ;
    wire \CLMA_106_129/ntCYA ;
    wire \CLMA_106_129/ntCYB ;
    wire \CLMA_106_129/ntRS_P ;
    wire \CLMA_106_133/ntCECO ;
    wire \CLMA_106_133/ntY1 ;
    wire \CLMA_106_136/ntCECO ;
    wire \CLMA_106_136/ntRSCO ;
    wire \CLMA_106_136/ntRS_P ;
    wire \CLMA_106_137/ntCECO ;
    wire \CLMA_106_137/ntCYA ;
    wire \CLMA_106_137/ntCYB ;
    wire \CLMA_106_137/ntCYC ;
    wire \CLMA_106_137/ntY0 ;
    wire \CLMA_106_137/ntY1 ;
    wire \CLMA_106_137/ntY2 ;
    wire \CLMA_106_137/ntY3 ;
    wire \CLMA_106_141/ntCECO ;
    wire \CLMA_106_141/ntCYA ;
    wire \CLMA_106_141/ntCYB ;
    wire \CLMA_106_141/ntCYC ;
    wire \CLMA_106_141/ntY0 ;
    wire \CLMA_106_141/ntY1 ;
    wire \CLMA_106_141/ntY2 ;
    wire \CLMA_106_141/ntY3 ;
    wire \CLMA_106_145/ntCECO ;
    wire \CLMA_106_145/ntCYA ;
    wire \CLMA_106_145/ntRSCO ;
    wire \CLMA_106_145/ntY0 ;
    wire \CLMA_106_145/ntY1 ;
    wire \CLMA_114_100/ntCECO ;
    wire \CLMA_114_100/ntRSCO ;
    wire \CLMA_114_100/ntRS_P ;
    wire \CLMA_114_100/ntY0 ;
    wire \CLMS_102_125/ntCYA ;
    wire \CLMS_102_125/ntCYB ;
    wire \CLMS_102_125/ntCYC ;
    wire \CLMS_102_129/ntCECO ;
    wire \CLMS_102_129/ntCYA ;
    wire \CLMS_102_129/ntRSCO ;
    wire \CLMS_102_129/ntRS_P ;
    wire \CLMS_102_137/ntCECO ;
    wire \CLMS_102_137/ntRSCO ;
    wire \CLMS_102_137/ntRS_P ;
    wire \CLMS_114_109/ntCECO ;
    wire \CLMS_114_109/ntRSCO ;
    wire \CLMS_114_109/ntRS_P ;
    wire \CLMS_114_109/ntY0 ;
    wire \CLMS_114_109/ntY1 ;
    wire \CLMS_114_109/ntY2 ;
    wire \CLMS_114_109/ntY3 ;
    wire \IOL_151_9/MIPI_OUT/_N1 ;
    wire \IOL_151_9/MIPI_OUT/_N3 ;
    wire \IOL_151_86/MIPI_OUT/_N1 ;
    wire \IOL_151_86/MIPI_OUT/_N3 ;
    wire \IOL_151_114/MIPI_OUT/_N1 ;
    wire \IOL_151_114/MIPI_OUT/_N3 ;
    wire [11:0] N13;
    wire _N0;
    wire _N1;
    wire _N141;
    wire _N145;
    wire \clk50M_ibuf/ntD ;
    wire clk200M;
    wire [12:0] \dac_u/N9.co ;
    wire \dac_u/_N129 ;
    wire \dac_u/_N133 ;
    wire [11:0] \dac_u/count ;
    wire \i2s_u/N226_inv ;
    wire \i2s_u/N342 ;
    wire \i2s_u/_N118 ;
    wire \i2s_u/_N122 ;
    wire \i2s_u/_N176 ;
    wire \i2s_u/_N189 ;
    wire \i2s_u/_N190 ;
    wire \i2s_u/_N196 ;
    wire \i2s_u/_N210 ;
    wire \i2s_u/_N215 ;
    wire \i2s_u/_N227 ;
    wire \i2s_u/_N260 ;
    wire \i2s_u/_N282 ;
    wire \i2s_u/_N346 ;
    wire \i2s_u/_N347 ;
    wire \i2s_u/_N354 ;
    wire \i2s_u/ready ;
    wire [15:0] \i2s_u/sck_cnt ;
    wire [23:0] \i2s_u/shift_reg_l ;
    wire [21:0] \i2s_u/ws_cnt ;
    wire [23:0] mic_data;
    wire \mic_out_obuf/ntO ;
    wire \mic_sck_obuf/ntO ;
    wire \mic_sd_ibuf/ntD ;
    wire \mic_ws_obuf/ntO ;
    wire ntR0;
    wire ntR1;
    wire ntR2;
    wire ntR3;
    wire ntR4;
    wire ntR5;
    wire ntR6;
    wire ntR7;
    wire ntR8;
    wire ntR9;
    wire ntR10;
    wire ntR11;
    wire ntR12;
    wire ntR13;
    wire nt_mic_sck;
    wire nt_mic_sd;
    wire nt_mic_ws;
    wire nt_rst_n;
    wire ntclkbufg_0;
    wire ntclkbufg_1;
    wire \rst_n_ibuf/ntD ;

    V_LUT5 /* GND_2/FYA/FY */ #(
            .INIT(32'b00000000000000000000000000000000))
        \CLMA_78_304/FYA/FY  (
            .Y (ntR11),
            .I0 (1'b0),
            .I1 (1'b0),
            .I2 (1'b0),
            .I3 (1'b0),
            .I4 (1'b0));
	// LUT = 1'b0 ;

    V_BUF \CLMA_98_125/CEMUX/V_BUF  (
            .Z (\CLMA_98_125/ntCECO ),
            .I (1'b1));
	// ../source/dac_out.v:12

    V_FFASYN /* dac_u/count[0]/opit_0_inv_L5Q_perm/FF0/FF */ #(
            .GRS_EN("TRUE"), 
            .SET_RESET("RESET"), 
            .LRS_EN("TRUE"), 
            .INIT(1'b0))
        \CLMA_98_125/FF0/FF  (
            .Q (\dac_u/count [0] ),
            .CE (\CLMA_98_125/ntCECO ),
            .CK (ntclkbufg_1),
            .D (\CLMA_98_125/ntY0 ),
            .SR (\CLMA_98_125/ntRSCO ));
	// ../source/dac_out.v:12

    V_LUT5 /* dac_u/count[0]/opit_0_inv_L5Q_perm/FYA/FY */ #(
            .INIT(32'b00000000000000001111111111111111))
        \CLMA_98_125/FYA/FY  (
            .Y (\CLMA_98_125/ntY0 ),
            .I0 (1'b0),
            .I1 (1'b0),
            .I2 (1'b0),
            .I3 (1'b0),
            .I4 (\dac_u/count [0] ));
	// LUT = ~I4 ;
	// ../source/dac_out.v:12

    V_INV \CLMA_98_125/LRSPOLMUX/V_INV  (
            .Z (\CLMA_98_125/ntRS_P ),
            .I (nt_rst_n));
	// ../source/dac_out.v:12

    V_BUF \CLMA_98_125/RSMUX/V_BUF  (
            .Z (\CLMA_98_125/ntRSCO ),
            .I (\CLMA_98_125/ntRS_P ));
	// ../source/dac_out.v:12

    V_BUF \CLMA_98_132/CEMUX/V_BUF  (
            .Z (\CLMA_98_132/ntCECO ),
            .I (1'b1));
	// ../source/dac_out.v:12

    V_FFASYN /* dac_u/count[2]/opit_0_inv_A2Q21/FF0/FF */ #(
            .GRS_EN("TRUE"), 
            .SET_RESET("RESET"), 
            .LRS_EN("TRUE"), 
            .INIT(1'b0))
        \CLMA_98_132/FF0/FF  (
            .Q (\dac_u/count [1] ),
            .CE (\CLMA_98_132/ntCECO ),
            .CK (ntclkbufg_1),
            .D (\CLMA_98_132/ntY0 ),
            .SR (ntR1));
	// ../source/dac_out.v:12

    V_FFASYN /* dac_u/count[2]/opit_0_inv_A2Q21/FF1/FF */ #(
            .GRS_EN("TRUE"), 
            .SET_RESET("RESET"), 
            .LRS_EN("TRUE"), 
            .INIT(1'b0))
        \CLMA_98_132/FF1/FF  (
            .Q (\dac_u/count [2] ),
            .CE (\CLMA_98_132/ntCECO ),
            .CK (ntclkbufg_1),
            .D (\CLMA_98_132/ntY1 ),
            .SR (ntR1));
	// ../source/dac_out.v:12

    V_FFASYN /* dac_u/count[4]/opit_0_inv_A2Q21/FF2/FF */ #(
            .GRS_EN("TRUE"), 
            .SET_RESET("RESET"), 
            .LRS_EN("TRUE"), 
            .INIT(1'b0))
        \CLMA_98_132/FF2/FF  (
            .Q (\dac_u/count [3] ),
            .CE (\CLMA_98_132/ntCECO ),
            .CK (ntclkbufg_1),
            .D (\CLMA_98_132/ntY2 ),
            .SR (ntR1));
	// ../source/dac_out.v:12

    V_FFASYN /* dac_u/count[4]/opit_0_inv_A2Q21/FF3/FF */ #(
            .GRS_EN("TRUE"), 
            .SET_RESET("RESET"), 
            .LRS_EN("TRUE"), 
            .INIT(1'b0))
        \CLMA_98_132/FF3/FF  (
            .Q (\dac_u/count [4] ),
            .CE (\CLMA_98_132/ntCECO ),
            .CK (ntclkbufg_1),
            .D (\CLMA_98_132/ntY3 ),
            .SR (ntR1));
	// ../source/dac_out.v:12

    V_LUT5CARRY /* dac_u/count[2]/opit_0_inv_A2Q21/FYA/V_FY */ #(
            .INIT(32'b01100110011001100000000000000000), 
            .ID_TO_LUT("FALSE"), 
            .CIN_TO_LUT("FALSE"), 
            .I4_TO_CARRY("TRUE"), 
            .I4_TO_LUT("FALSE"))
        \CLMA_98_132/FYA/V_FY  (
            .COUT (\CLMA_98_132/ntCYA ),
            .S (\CLMA_98_132/ntY0 ),
            .CIN (1'b0),
            .I0 (\dac_u/count [0] ),
            .I1 (\dac_u/count [1] ),
            .I2 (1'b0),
            .I3 (1'b0),
            .I4 (ntR13),
            .ID (1'b0));
	// LUT = I1^I0 ;
	// CARRY = (1'b0) ? CIN : (I4) ;
	// ../source/dac_out.v:12

    V_LUT5CARRY /* dac_u/count[2]/opit_0_inv_A2Q21/FYB/V_FY */ #(
            .INIT(32'b01111000011110001000000010000000), 
            .ID_TO_LUT("FALSE"), 
            .CIN_TO_LUT("FALSE"), 
            .I4_TO_CARRY("TRUE"), 
            .I4_TO_LUT("FALSE"))
        \CLMA_98_132/FYB/V_FY  (
            .COUT (\CLMA_98_132/ntCYB ),
            .S (\CLMA_98_132/ntY1 ),
            .CIN (\CLMA_98_132/ntCYA ),
            .I0 (\dac_u/count [0] ),
            .I1 (\dac_u/count [1] ),
            .I2 (\dac_u/count [2] ),
            .I3 (1'b0),
            .I4 (ntR10),
            .ID (1'b0));
	// LUT = (I0&I1&~I2)|(~I1&I2)|(~I0&I2) ;
	// CARRY = (I0&I1&I2) ? CIN : (I4) ;
	// ../source/dac_out.v:12

    V_LUT5CARRY /* dac_u/count[4]/opit_0_inv_A2Q21/FYC/V_FY */ #(
            .INIT(32'b01100110011001101100110011001100), 
            .ID_TO_LUT("FALSE"), 
            .CIN_TO_LUT("TRUE"), 
            .I4_TO_CARRY("TRUE"), 
            .I4_TO_LUT("FALSE"))
        \CLMA_98_132/FYC/V_FY  (
            .COUT (\CLMA_98_132/ntCYC ),
            .S (\CLMA_98_132/ntY2 ),
            .CIN (\CLMA_98_132/ntCYB ),
            .I0 (1'b0),
            .I1 (\dac_u/count [3] ),
            .I2 (1'b0),
            .I3 (1'b0),
            .I4 (ntR10),
            .ID (1'b0));
	// LUT = I1^CIN ;
	// CARRY = (I1) ? CIN : (I4) ;
	// ../source/dac_out.v:12

    V_LUT5CARRY /* dac_u/count[4]/opit_0_inv_A2Q21/FYD/V_FY */ #(
            .INIT(32'b01100110011001101100110011001100), 
            .ID_TO_LUT("FALSE"), 
            .CIN_TO_LUT("TRUE"), 
            .I4_TO_CARRY("TRUE"), 
            .I4_TO_LUT("FALSE"))
        \CLMA_98_132/FYD/V_FY  (
            .COUT (\dac_u/_N129 ),
            .S (\CLMA_98_132/ntY3 ),
            .CIN (\CLMA_98_132/ntCYC ),
            .I0 (1'b0),
            .I1 (\dac_u/count [4] ),
            .I2 (1'b0),
            .I3 (1'b0),
            .I4 (ntR10),
            .ID (1'b0));
	// LUT = I1^CIN ;
	// CARRY = (I1) ? CIN : (I4) ;
	// ../source/dac_out.v:12

    V_INV \CLMA_98_132/LRSPOLMUX/V_INV  (
            .Z (\CLMA_98_132/ntRS_P ),
            .I (nt_rst_n));
	// ../source/dac_out.v:12

    V_BUF \CLMA_98_132/RSMUX/V_BUF  (
            .Z (ntR1),
            .I (\CLMA_98_132/ntRS_P ));
	// ../source/dac_out.v:12

    V_BUF \CLMA_98_136/CEMUX/V_BUF  (
            .Z (\CLMA_98_136/ntCECO ),
            .I (1'b1));
	// ../source/dac_out.v:12

    V_FFASYN /* dac_u/count[6]/opit_0_inv_A2Q21/FF0/FF */ #(
            .GRS_EN("TRUE"), 
            .SET_RESET("RESET"), 
            .LRS_EN("TRUE"), 
            .INIT(1'b0))
        \CLMA_98_136/FF0/FF  (
            .Q (\dac_u/count [5] ),
            .CE (\CLMA_98_136/ntCECO ),
            .CK (ntclkbufg_1),
            .D (\CLMA_98_136/ntY0 ),
            .SR (ntR0));
	// ../source/dac_out.v:12

    V_FFASYN /* dac_u/count[6]/opit_0_inv_A2Q21/FF1/FF */ #(
            .GRS_EN("TRUE"), 
            .SET_RESET("RESET"), 
            .LRS_EN("TRUE"), 
            .INIT(1'b0))
        \CLMA_98_136/FF1/FF  (
            .Q (\dac_u/count [6] ),
            .CE (\CLMA_98_136/ntCECO ),
            .CK (ntclkbufg_1),
            .D (\CLMA_98_136/ntY1 ),
            .SR (ntR0));
	// ../source/dac_out.v:12

    V_FFASYN /* dac_u/count[8]/opit_0_inv_A2Q21/FF2/FF */ #(
            .GRS_EN("TRUE"), 
            .SET_RESET("RESET"), 
            .LRS_EN("TRUE"), 
            .INIT(1'b0))
        \CLMA_98_136/FF2/FF  (
            .Q (\dac_u/count [7] ),
            .CE (\CLMA_98_136/ntCECO ),
            .CK (ntclkbufg_1),
            .D (\CLMA_98_136/ntY2 ),
            .SR (ntR0));
	// ../source/dac_out.v:12

    V_FFASYN /* dac_u/count[8]/opit_0_inv_A2Q21/FF3/FF */ #(
            .GRS_EN("TRUE"), 
            .SET_RESET("RESET"), 
            .LRS_EN("TRUE"), 
            .INIT(1'b0))
        \CLMA_98_136/FF3/FF  (
            .Q (\dac_u/count [8] ),
            .CE (\CLMA_98_136/ntCECO ),
            .CK (ntclkbufg_1),
            .D (\CLMA_98_136/ntY3 ),
            .SR (ntR0));
	// ../source/dac_out.v:12

    V_LUT5CARRY /* dac_u/count[6]/opit_0_inv_A2Q21/FYA/V_FY */ #(
            .INIT(32'b01100110011001101100110011001100), 
            .ID_TO_LUT("FALSE"), 
            .CIN_TO_LUT("TRUE"), 
            .I4_TO_CARRY("TRUE"), 
            .I4_TO_LUT("FALSE"))
        \CLMA_98_136/FYA/V_FY  (
            .COUT (\CLMA_98_136/ntCYA ),
            .S (\CLMA_98_136/ntY0 ),
            .CIN (\dac_u/_N129 ),
            .I0 (1'b0),
            .I1 (\dac_u/count [5] ),
            .I2 (1'b0),
            .I3 (1'b0),
            .I4 (ntR10),
            .ID (1'b0));
	// LUT = I1^CIN ;
	// CARRY = (I1) ? CIN : (I4) ;
	// ../source/dac_out.v:12

    V_LUT5CARRY /* dac_u/count[6]/opit_0_inv_A2Q21/FYB/V_FY */ #(
            .INIT(32'b01100110011001101100110011001100), 
            .ID_TO_LUT("FALSE"), 
            .CIN_TO_LUT("TRUE"), 
            .I4_TO_CARRY("TRUE"), 
            .I4_TO_LUT("FALSE"))
        \CLMA_98_136/FYB/V_FY  (
            .COUT (\CLMA_98_136/ntCYB ),
            .S (\CLMA_98_136/ntY1 ),
            .CIN (\CLMA_98_136/ntCYA ),
            .I0 (1'b0),
            .I1 (\dac_u/count [6] ),
            .I2 (1'b0),
            .I3 (1'b0),
            .I4 (ntR10),
            .ID (1'b0));
	// LUT = I1^CIN ;
	// CARRY = (I1) ? CIN : (I4) ;
	// ../source/dac_out.v:12

    V_LUT5CARRY /* dac_u/count[8]/opit_0_inv_A2Q21/FYC/V_FY */ #(
            .INIT(32'b01100110011001101100110011001100), 
            .ID_TO_LUT("FALSE"), 
            .CIN_TO_LUT("TRUE"), 
            .I4_TO_CARRY("TRUE"), 
            .I4_TO_LUT("FALSE"))
        \CLMA_98_136/FYC/V_FY  (
            .COUT (\CLMA_98_136/ntCYC ),
            .S (\CLMA_98_136/ntY2 ),
            .CIN (\CLMA_98_136/ntCYB ),
            .I0 (1'b0),
            .I1 (\dac_u/count [7] ),
            .I2 (1'b0),
            .I3 (1'b0),
            .I4 (ntR10),
            .ID (1'b0));
	// LUT = I1^CIN ;
	// CARRY = (I1) ? CIN : (I4) ;
	// ../source/dac_out.v:12

    V_LUT5CARRY /* dac_u/count[8]/opit_0_inv_A2Q21/FYD/V_FY */ #(
            .INIT(32'b01100110011001101100110011001100), 
            .ID_TO_LUT("FALSE"), 
            .CIN_TO_LUT("TRUE"), 
            .I4_TO_CARRY("TRUE"), 
            .I4_TO_LUT("FALSE"))
        \CLMA_98_136/FYD/V_FY  (
            .COUT (\dac_u/_N133 ),
            .S (\CLMA_98_136/ntY3 ),
            .CIN (\CLMA_98_136/ntCYC ),
            .I0 (1'b0),
            .I1 (\dac_u/count [8] ),
            .I2 (1'b0),
            .I3 (1'b0),
            .I4 (ntR10),
            .ID (1'b0));
	// LUT = I1^CIN ;
	// CARRY = (I1) ? CIN : (I4) ;
	// ../source/dac_out.v:12

    V_BUF \CLMA_98_136/RSMUX/V_BUF  (
            .Z (ntR0),
            .I (ntR1));
	// ../source/dac_out.v:12

    V_BUF \CLMA_98_140/CEMUX/V_BUF  (
            .Z (\CLMA_98_140/ntCECO ),
            .I (1'b1));
	// ../source/dac_out.v:12

    V_FFASYN /* dac_u/count[10]/opit_0_inv_A2Q21/FF0/FF */ #(
            .GRS_EN("TRUE"), 
            .SET_RESET("RESET"), 
            .LRS_EN("TRUE"), 
            .INIT(1'b0))
        \CLMA_98_140/FF0/FF  (
            .Q (\dac_u/count [9] ),
            .CE (\CLMA_98_140/ntCECO ),
            .CK (ntclkbufg_1),
            .D (\CLMA_98_140/ntY0 ),
            .SR (\CLMA_98_140/ntRSCO ));
	// ../source/dac_out.v:12

    V_FFASYN /* dac_u/count[10]/opit_0_inv_A2Q21/FF1/FF */ #(
            .GRS_EN("TRUE"), 
            .SET_RESET("RESET"), 
            .LRS_EN("TRUE"), 
            .INIT(1'b0))
        \CLMA_98_140/FF1/FF  (
            .Q (\dac_u/count [10] ),
            .CE (\CLMA_98_140/ntCECO ),
            .CK (ntclkbufg_1),
            .D (\CLMA_98_140/ntY1 ),
            .SR (\CLMA_98_140/ntRSCO ));
	// ../source/dac_out.v:12

    V_FFASYN /* dac_u/count[11]/opit_0_inv_AQ/FF2/FF */ #(
            .GRS_EN("TRUE"), 
            .SET_RESET("RESET"), 
            .LRS_EN("TRUE"), 
            .INIT(1'b0))
        \CLMA_98_140/FF2/FF  (
            .Q (\dac_u/count [11] ),
            .CE (\CLMA_98_140/ntCECO ),
            .CK (ntclkbufg_1),
            .D (\CLMA_98_140/ntY2 ),
            .SR (\CLMA_98_140/ntRSCO ));
	// ../source/dac_out.v:12

    V_LUT5CARRY /* dac_u/count[10]/opit_0_inv_A2Q21/FYA/V_FY */ #(
            .INIT(32'b01100110011001101100110011001100), 
            .ID_TO_LUT("FALSE"), 
            .CIN_TO_LUT("TRUE"), 
            .I4_TO_CARRY("TRUE"), 
            .I4_TO_LUT("FALSE"))
        \CLMA_98_140/FYA/V_FY  (
            .COUT (\CLMA_98_140/ntCYA ),
            .S (\CLMA_98_140/ntY0 ),
            .CIN (\dac_u/_N133 ),
            .I0 (1'b0),
            .I1 (\dac_u/count [9] ),
            .I2 (1'b0),
            .I3 (1'b0),
            .I4 (ntR10),
            .ID (1'b0));
	// LUT = I1^CIN ;
	// CARRY = (I1) ? CIN : (I4) ;
	// ../source/dac_out.v:12

    V_LUT5CARRY /* dac_u/count[10]/opit_0_inv_A2Q21/FYB/V_FY */ #(
            .INIT(32'b01100110011001101100110011001100), 
            .ID_TO_LUT("FALSE"), 
            .CIN_TO_LUT("TRUE"), 
            .I4_TO_CARRY("TRUE"), 
            .I4_TO_LUT("FALSE"))
        \CLMA_98_140/FYB/V_FY  (
            .COUT (\CLMA_98_140/ntCYB ),
            .S (\CLMA_98_140/ntY1 ),
            .CIN (\CLMA_98_140/ntCYA ),
            .I0 (1'b0),
            .I1 (\dac_u/count [10] ),
            .I2 (1'b0),
            .I3 (1'b0),
            .I4 (ntR10),
            .ID (1'b0));
	// LUT = I1^CIN ;
	// CARRY = (I1) ? CIN : (I4) ;
	// ../source/dac_out.v:12

    V_LUT5CARRY /* dac_u/count[11]/opit_0_inv_AQ/FYC/V_FY */ #(
            .INIT(32'b01100110011001101100110011001100), 
            .ID_TO_LUT("FALSE"), 
            .CIN_TO_LUT("TRUE"), 
            .I4_TO_CARRY("TRUE"), 
            .I4_TO_LUT("FALSE"))
        \CLMA_98_140/FYC/V_FY  (
            .COUT (),
            .S (\CLMA_98_140/ntY2 ),
            .CIN (\CLMA_98_140/ntCYB ),
            .I0 (1'b0),
            .I1 (\dac_u/count [11] ),
            .I2 (1'b0),
            .I3 (1'b0),
            .I4 (ntR10),
            .ID (1'b0));
	// LUT = I1^CIN ;
	// CARRY = (I1) ? CIN : (I4) ;
	// ../source/dac_out.v:12

    V_BUF \CLMA_98_140/RSMUX/V_BUF  (
            .Z (\CLMA_98_140/ntRSCO ),
            .I (ntR0));
	// ../source/dac_out.v:12

    V_BUF \CLMA_102_128/CEMUX/V_BUF  (
            .Z (\CLMA_102_128/ntCECO ),
            .I (\i2s_u/ready ));
	// ../source/i2s_top.v:114

    V_FFASYN /* i2s_u/ldata[13]/opit_0_inv/FF0/FF */ #(
            .GRS_EN("TRUE"), 
            .SET_RESET("RESET"), 
            .LRS_EN("TRUE"), 
            .INIT(1'b0))
        \CLMA_102_128/FF0/FF  (
            .Q (mic_data[13]),
            .CE (\CLMA_102_128/ntCECO ),
            .CK (ntclkbufg_0),
            .D (\i2s_u/shift_reg_l [13] ),
            .SR (ntR3));
	// ../source/i2s_top.v:114

    V_FFASYN /* i2s_u/ldata[12]/opit_0_inv/FF1/FF */ #(
            .GRS_EN("TRUE"), 
            .SET_RESET("RESET"), 
            .LRS_EN("TRUE"), 
            .INIT(1'b0))
        \CLMA_102_128/FF1/FF  (
            .Q (mic_data[12]),
            .CE (\CLMA_102_128/ntCECO ),
            .CK (ntclkbufg_0),
            .D (\i2s_u/shift_reg_l [12] ),
            .SR (ntR3));
	// ../source/i2s_top.v:114

    V_INV \CLMA_102_128/LRSPOLMUX/V_INV  (
            .Z (\CLMA_102_128/ntRS_P ),
            .I (nt_rst_n));
	// ../source/i2s_top.v:114

    V_BUF \CLMA_102_128/RSMUX/V_BUF  (
            .Z (ntR3),
            .I (\CLMA_102_128/ntRS_P ));
	// ../source/i2s_top.v:114

    V_BUF \CLMA_102_132/CEMUX/V_BUF  (
            .Z (ntR8),
            .I (\i2s_u/N342 ));
	// ../source/i2s_top.v:52

    V_FFASYN /* i2s_u/shift_reg_l[7]/opit_0_inv/FF0/FF */ #(
            .GRS_EN("TRUE"), 
            .SET_RESET("RESET"), 
            .LRS_EN("TRUE"), 
            .INIT(1'b0))
        \CLMA_102_132/FF0/FF  (
            .Q (\i2s_u/shift_reg_l [7] ),
            .CE (ntR8),
            .CK (ntclkbufg_0),
            .D (\i2s_u/shift_reg_l [6] ),
            .SR (ntR2));
	// ../source/i2s_top.v:52

    V_FFASYN /* i2s_u/shift_reg_l[11]/opit_0_inv/FF1/FF */ #(
            .GRS_EN("TRUE"), 
            .SET_RESET("RESET"), 
            .LRS_EN("TRUE"), 
            .INIT(1'b0))
        \CLMA_102_132/FF1/FF  (
            .Q (\i2s_u/shift_reg_l [11] ),
            .CE (ntR8),
            .CK (ntclkbufg_0),
            .D (\i2s_u/shift_reg_l [10] ),
            .SR (ntR2));
	// ../source/i2s_top.v:52

    V_FFASYN /* i2s_u/shift_reg_l[9]/opit_0_inv/FF2/FF */ #(
            .GRS_EN("TRUE"), 
            .SET_RESET("RESET"), 
            .LRS_EN("TRUE"), 
            .INIT(1'b0))
        \CLMA_102_132/FF2/FF  (
            .Q (\i2s_u/shift_reg_l [9] ),
            .CE (ntR8),
            .CK (ntclkbufg_0),
            .D (\i2s_u/shift_reg_l [8] ),
            .SR (ntR2));
	// ../source/i2s_top.v:52

    V_FFASYN /* i2s_u/shift_reg_l[10]/opit_0_inv/FF3/FF */ #(
            .GRS_EN("TRUE"), 
            .SET_RESET("RESET"), 
            .LRS_EN("TRUE"), 
            .INIT(1'b0))
        \CLMA_102_132/FF3/FF  (
            .Q (\i2s_u/shift_reg_l [10] ),
            .CE (ntR8),
            .CK (ntclkbufg_0),
            .D (\i2s_u/shift_reg_l [9] ),
            .SR (ntR2));
	// ../source/i2s_top.v:52

    V_BUF \CLMA_102_132/RSMUX/V_BUF  (
            .Z (ntR2),
            .I (ntR3));
	// ../source/i2s_top.v:52

    V_BUF \CLMA_102_136/CEMUX/V_BUF  (
            .Z (\CLMA_102_136/ntCECO ),
            .I (ntR8));
	// ../source/i2s_top.v:52

    V_FFASYN /* i2s_u/shift_reg_l[1]/opit_0_inv/FF0/FF */ #(
            .GRS_EN("TRUE"), 
            .SET_RESET("RESET"), 
            .LRS_EN("TRUE"), 
            .INIT(1'b0))
        \CLMA_102_136/FF0/FF  (
            .Q (\i2s_u/shift_reg_l [1] ),
            .CE (\CLMA_102_136/ntCECO ),
            .CK (ntclkbufg_0),
            .D (\i2s_u/shift_reg_l [0] ),
            .SR (\CLMA_102_136/ntRSCO ));
	// ../source/i2s_top.v:52

    V_FFASYN /* i2s_u/shift_reg_l[6]/opit_0_inv/FF1/FF */ #(
            .GRS_EN("TRUE"), 
            .SET_RESET("RESET"), 
            .LRS_EN("TRUE"), 
            .INIT(1'b0))
        \CLMA_102_136/FF1/FF  (
            .Q (\i2s_u/shift_reg_l [6] ),
            .CE (\CLMA_102_136/ntCECO ),
            .CK (ntclkbufg_0),
            .D (\i2s_u/shift_reg_l [5] ),
            .SR (\CLMA_102_136/ntRSCO ));
	// ../source/i2s_top.v:52

    V_FFASYN /* i2s_u/shift_reg_l[5]/opit_0_inv/FF2/FF */ #(
            .GRS_EN("TRUE"), 
            .SET_RESET("RESET"), 
            .LRS_EN("TRUE"), 
            .INIT(1'b0))
        \CLMA_102_136/FF2/FF  (
            .Q (\i2s_u/shift_reg_l [5] ),
            .CE (\CLMA_102_136/ntCECO ),
            .CK (ntclkbufg_0),
            .D (\i2s_u/shift_reg_l [4] ),
            .SR (\CLMA_102_136/ntRSCO ));
	// ../source/i2s_top.v:52

    V_FFASYN /* i2s_u/shift_reg_l[4]/opit_0_inv/FF3/FF */ #(
            .GRS_EN("TRUE"), 
            .SET_RESET("RESET"), 
            .LRS_EN("TRUE"), 
            .INIT(1'b0))
        \CLMA_102_136/FF3/FF  (
            .Q (\i2s_u/shift_reg_l [4] ),
            .CE (\CLMA_102_136/ntCECO ),
            .CK (ntclkbufg_0),
            .D (\i2s_u/shift_reg_l [3] ),
            .SR (\CLMA_102_136/ntRSCO ));
	// ../source/i2s_top.v:52

    V_FFASYN /* i2s_u/shift_reg_l[8]/opit_0_inv/FFAB/FF */ #(
            .GRS_EN("TRUE"), 
            .SET_RESET("RESET"), 
            .LRS_EN("TRUE"), 
            .INIT(1'b0))
        \CLMA_102_136/FFAB/FF  (
            .Q (\i2s_u/shift_reg_l [8] ),
            .CE (\CLMA_102_136/ntCECO ),
            .CK (ntclkbufg_0),
            .D (\i2s_u/shift_reg_l [7] ),
            .SR (\CLMA_102_136/ntRSCO ));
	// ../source/i2s_top.v:52

    V_FFASYN /* i2s_u/shift_reg_l[12]/opit_0_inv/FFCD/FF */ #(
            .GRS_EN("TRUE"), 
            .SET_RESET("RESET"), 
            .LRS_EN("TRUE"), 
            .INIT(1'b0))
        \CLMA_102_136/FFCD/FF  (
            .Q (\i2s_u/shift_reg_l [12] ),
            .CE (\CLMA_102_136/ntCECO ),
            .CK (ntclkbufg_0),
            .D (\i2s_u/shift_reg_l [11] ),
            .SR (\CLMA_102_136/ntRSCO ));
	// ../source/i2s_top.v:52

    V_BUF \CLMA_102_136/RSMUX/V_BUF  (
            .Z (\CLMA_102_136/ntRSCO ),
            .I (ntR2));
	// ../source/i2s_top.v:52

    V_LUT5CARRY /* N5_0_1/gateop_A2/FYA/V_FY */ #(
            .INIT(32'b10011001100110010000000000000000), 
            .ID_TO_LUT("FALSE"), 
            .CIN_TO_LUT("FALSE"), 
            .I4_TO_CARRY("TRUE"), 
            .I4_TO_LUT("FALSE"))
        \CLMA_106_121/FYA/V_FY  (
            .COUT (\CLMA_106_121/ntCYA ),
            .S (N13[1]),
            .CIN (1'b0),
            .I0 (mic_data[12]),
            .I1 (mic_data[13]),
            .I2 (1'b0),
            .I3 (1'b0),
            .I4 (ntR12),
            .ID (1'b0));
	// LUT = ~I1^I0 ;
	// CARRY = (1'b0) ? CIN : (I4) ;
	// ../source/top.v:15

    V_LUT5CARRY /* N5_0_1/gateop_A2/FYB/V_FY */ #(
            .INIT(32'b11100001111000011111111011111110), 
            .ID_TO_LUT("FALSE"), 
            .CIN_TO_LUT("FALSE"), 
            .I4_TO_CARRY("TRUE"), 
            .I4_TO_LUT("FALSE"))
        \CLMA_106_121/FYB/V_FY  (
            .COUT (\CLMA_106_121/ntCYB ),
            .S (N13[2]),
            .CIN (\CLMA_106_121/ntCYA ),
            .I0 (mic_data[12]),
            .I1 (mic_data[13]),
            .I2 (mic_data[14]),
            .I3 (1'b0),
            .I4 (ntR9),
            .ID (1'b0));
	// LUT = (~I0&~I1&~I2)|(I1&I2)|(I0&I2) ;
	// CARRY = ((I2)|(I1)|(I0)) ? CIN : (I4) ;
	// ../source/top.v:15

    V_LUT5CARRY /* N5_0_3/gateop_A2/FYC/V_FY */ #(
            .INIT(32'b10011001100110010011001100110011), 
            .ID_TO_LUT("FALSE"), 
            .CIN_TO_LUT("TRUE"), 
            .I4_TO_CARRY("TRUE"), 
            .I4_TO_LUT("FALSE"))
        \CLMA_106_121/FYC/V_FY  (
            .COUT (\CLMA_106_121/ntCYC ),
            .S (N13[3]),
            .CIN (\CLMA_106_121/ntCYB ),
            .I0 (1'b0),
            .I1 (mic_data[15]),
            .I2 (1'b0),
            .I3 (1'b0),
            .I4 (ntR12),
            .ID (1'b0));
	// LUT = ~I1^CIN ;
	// CARRY = (~I1) ? CIN : (I4) ;
	// ../source/top.v:15

    V_LUT5CARRY /* N5_0_3/gateop_A2/FYD/V_FY */ #(
            .INIT(32'b10011001100110010011001100110011), 
            .ID_TO_LUT("FALSE"), 
            .CIN_TO_LUT("TRUE"), 
            .I4_TO_CARRY("TRUE"), 
            .I4_TO_LUT("FALSE"))
        \CLMA_106_121/FYD/V_FY  (
            .COUT (_N141),
            .S (N13[4]),
            .CIN (\CLMA_106_121/ntCYC ),
            .I0 (1'b0),
            .I1 (mic_data[16]),
            .I2 (1'b0),
            .I3 (1'b0),
            .I4 (ntR12),
            .ID (1'b0));
	// LUT = ~I1^CIN ;
	// CARRY = (~I1) ? CIN : (I4) ;
	// ../source/top.v:15

    V_LUT5CARRY /* N5_0_5/gateop_A2/FYA/V_FY */ #(
            .INIT(32'b10011001100110010011001100110011), 
            .ID_TO_LUT("FALSE"), 
            .CIN_TO_LUT("TRUE"), 
            .I4_TO_CARRY("TRUE"), 
            .I4_TO_LUT("FALSE"))
        \CLMA_106_125/FYA/V_FY  (
            .COUT (\CLMA_106_125/ntCYA ),
            .S (N13[5]),
            .CIN (_N141),
            .I0 (1'b0),
            .I1 (mic_data[17]),
            .I2 (1'b0),
            .I3 (1'b0),
            .I4 (ntR12),
            .ID (1'b0));
	// LUT = ~I1^CIN ;
	// CARRY = (~I1) ? CIN : (I4) ;
	// ../source/top.v:15

    V_LUT5CARRY /* N5_0_5/gateop_A2/FYB/V_FY */ #(
            .INIT(32'b10011001100110010011001100110011), 
            .ID_TO_LUT("FALSE"), 
            .CIN_TO_LUT("TRUE"), 
            .I4_TO_CARRY("TRUE"), 
            .I4_TO_LUT("FALSE"))
        \CLMA_106_125/FYB/V_FY  (
            .COUT (\CLMA_106_125/ntCYB ),
            .S (N13[6]),
            .CIN (\CLMA_106_125/ntCYA ),
            .I0 (1'b0),
            .I1 (mic_data[18]),
            .I2 (1'b0),
            .I3 (1'b0),
            .I4 (ntR12),
            .ID (1'b0));
	// LUT = ~I1^CIN ;
	// CARRY = (~I1) ? CIN : (I4) ;
	// ../source/top.v:15

    V_LUT5CARRY /* N5_0_7/gateop_A2/FYC/V_FY */ #(
            .INIT(32'b10011001100110010011001100110011), 
            .ID_TO_LUT("FALSE"), 
            .CIN_TO_LUT("TRUE"), 
            .I4_TO_CARRY("TRUE"), 
            .I4_TO_LUT("FALSE"))
        \CLMA_106_125/FYC/V_FY  (
            .COUT (\CLMA_106_125/ntCYC ),
            .S (N13[7]),
            .CIN (\CLMA_106_125/ntCYB ),
            .I0 (1'b0),
            .I1 (mic_data[19]),
            .I2 (1'b0),
            .I3 (1'b0),
            .I4 (ntR12),
            .ID (1'b0));
	// LUT = ~I1^CIN ;
	// CARRY = (~I1) ? CIN : (I4) ;
	// ../source/top.v:15

    V_LUT5CARRY /* N5_0_7/gateop_A2/FYD/V_FY */ #(
            .INIT(32'b10011001100110010011001100110011), 
            .ID_TO_LUT("FALSE"), 
            .CIN_TO_LUT("TRUE"), 
            .I4_TO_CARRY("TRUE"), 
            .I4_TO_LUT("FALSE"))
        \CLMA_106_125/FYD/V_FY  (
            .COUT (_N145),
            .S (N13[8]),
            .CIN (\CLMA_106_125/ntCYC ),
            .I0 (1'b0),
            .I1 (mic_data[20]),
            .I2 (1'b0),
            .I3 (1'b0),
            .I4 (ntR12),
            .ID (1'b0));
	// LUT = ~I1^CIN ;
	// CARRY = (~I1) ? CIN : (I4) ;
	// ../source/top.v:15

    V_BUF \CLMA_106_128/CEMUX/V_BUF  (
            .Z (\CLMA_106_128/ntCECO ),
            .I (\i2s_u/N342 ));
	// ../source/i2s_top.v:52

    V_FFASYN /* i2s_u/shift_reg_l[16]/opit_0_inv/FF0/FF */ #(
            .GRS_EN("TRUE"), 
            .SET_RESET("RESET"), 
            .LRS_EN("TRUE"), 
            .INIT(1'b0))
        \CLMA_106_128/FF0/FF  (
            .Q (\i2s_u/shift_reg_l [16] ),
            .CE (\CLMA_106_128/ntCECO ),
            .CK (ntclkbufg_0),
            .D (\i2s_u/shift_reg_l [15] ),
            .SR (\CLMA_106_128/ntRSCO ));
	// ../source/i2s_top.v:52

    V_FFASYN /* i2s_u/shift_reg_l[15]/opit_0_inv/FF1/FF */ #(
            .GRS_EN("TRUE"), 
            .SET_RESET("RESET"), 
            .LRS_EN("TRUE"), 
            .INIT(1'b0))
        \CLMA_106_128/FF1/FF  (
            .Q (\i2s_u/shift_reg_l [15] ),
            .CE (\CLMA_106_128/ntCECO ),
            .CK (ntclkbufg_0),
            .D (\i2s_u/shift_reg_l [14] ),
            .SR (\CLMA_106_128/ntRSCO ));
	// ../source/i2s_top.v:52

    V_FFASYN /* i2s_u/shift_reg_l[18]/opit_0_inv/FF2/FF */ #(
            .GRS_EN("TRUE"), 
            .SET_RESET("RESET"), 
            .LRS_EN("TRUE"), 
            .INIT(1'b0))
        \CLMA_106_128/FF2/FF  (
            .Q (\i2s_u/shift_reg_l [18] ),
            .CE (\CLMA_106_128/ntCECO ),
            .CK (ntclkbufg_0),
            .D (\i2s_u/shift_reg_l [17] ),
            .SR (\CLMA_106_128/ntRSCO ));
	// ../source/i2s_top.v:52

    V_FFASYN /* i2s_u/shift_reg_l[17]/opit_0_inv/FF3/FF */ #(
            .GRS_EN("TRUE"), 
            .SET_RESET("RESET"), 
            .LRS_EN("TRUE"), 
            .INIT(1'b0))
        \CLMA_106_128/FF3/FF  (
            .Q (\i2s_u/shift_reg_l [17] ),
            .CE (\CLMA_106_128/ntCECO ),
            .CK (ntclkbufg_0),
            .D (\i2s_u/shift_reg_l [16] ),
            .SR (\CLMA_106_128/ntRSCO ));
	// ../source/i2s_top.v:52

    V_LUT5M /* i2s_u/N342_41/gateop/FYA/V_FY */ #(
            .INIT(32'b00000000110110000000000010101010))
        \CLMA_106_128/FYA/V_FY  (
            .Z (\i2s_u/_N189 ),
            .I0 (\i2s_u/ws_cnt [4] ),
            .I1 (\i2s_u/_N227 ),
            .I2 (\i2s_u/_N176 ),
            .I3 (\i2s_u/ws_cnt [9] ),
            .I4 (\i2s_u/ws_cnt [6] ),
            .ID (\i2s_u/_N210 ));

    V_LUT5 /* i2s_u/N342_134/gateop_perm/FYB/FYC */ #(
            .INIT(32'b00000101101000001010000000000000))
        \CLMA_106_128/FYB/FYC  (
            .Y (\i2s_u/_N282 ),
            .I0 (\i2s_u/ws_cnt [7] ),
            .I1 (1'b0),
            .I2 (\i2s_u/ws_cnt [4] ),
            .I3 (\i2s_u/ws_cnt [8] ),
            .I4 (\i2s_u/ws_cnt [5] ));
	// LUT = (I0&I2&I3&~I4)|(I0&I2&~I3&I4)|(~I0&~I2&I3&I4) ;

    V_LUT5 /* i2s_u/N342_130/gateop_perm/FYC/FY */ #(
            .INIT(32'b00001100111111110000110000000000))
        \CLMA_106_128/FYC/FY  (
            .Y (\i2s_u/_N210 ),
            .I0 (1'b0),
            .I1 (\i2s_u/_N282 ),
            .I2 (\i2s_u/ws_cnt [3] ),
            .I3 (\i2s_u/ws_cnt [2] ),
            .I4 (\i2s_u/_N215 ));
	// LUT = (~I3&I4)|(I1&~I2&I3) ;

    V_LUT5M /* i2s_u/N342_42/gateop/FYD/V_FYC */ #(
            .INIT(32'b00000000100000001010000010100000))
        \CLMA_106_128/FYD/V_FYC  (
            .Z (\i2s_u/_N190 ),
            .I0 (\i2s_u/ws_cnt [4] ),
            .I1 (\i2s_u/_N260 ),
            .I2 (\i2s_u/_N347 ),
            .I3 (\i2s_u/ws_cnt [7] ),
            .I4 (\i2s_u/ws_cnt [6] ),
            .ID (\i2s_u/_N196 ));

    V_INV \CLMA_106_128/LRSPOLMUX/V_INV  (
            .Z (\CLMA_106_128/ntRS_P ),
            .I (nt_rst_n));
	// ../source/i2s_top.v:52

    V_BUF \CLMA_106_128/RSMUX/V_BUF  (
            .Z (\CLMA_106_128/ntRSCO ),
            .I (\CLMA_106_128/ntRS_P ));
	// ../source/i2s_top.v:52

    V_BUF \CLMA_106_129/CEMUX/V_BUF  (
            .Z (\CLMA_106_129/ntCECO ),
            .I (\i2s_u/N342 ));
	// ../source/i2s_top.v:52

    V_FFASYN /* i2s_u/shift_reg_l[0]/opit_0_inv/FF0/FF */ #(
            .GRS_EN("TRUE"), 
            .SET_RESET("RESET"), 
            .LRS_EN("TRUE"), 
            .INIT(1'b0))
        \CLMA_106_129/FF0/FF  (
            .Q (\i2s_u/shift_reg_l [0] ),
            .CE (\CLMA_106_129/ntCECO ),
            .CK (ntclkbufg_0),
            .D (nt_mic_sd),
            .SR (ntR7));
	// ../source/i2s_top.v:52

    V_FFASYN /* i2s_u/shift_reg_l[14]/opit_0_inv/FF1/FF */ #(
            .GRS_EN("TRUE"), 
            .SET_RESET("RESET"), 
            .LRS_EN("TRUE"), 
            .INIT(1'b0))
        \CLMA_106_129/FF1/FF  (
            .Q (\i2s_u/shift_reg_l [14] ),
            .CE (\CLMA_106_129/ntCECO ),
            .CK (ntclkbufg_0),
            .D (\i2s_u/shift_reg_l [13] ),
            .SR (ntR7));
	// ../source/i2s_top.v:52

    V_FFASYN /* i2s_u/shift_reg_l[13]/opit_0_inv/FF2/FF */ #(
            .GRS_EN("TRUE"), 
            .SET_RESET("RESET"), 
            .LRS_EN("TRUE"), 
            .INIT(1'b0))
        \CLMA_106_129/FF2/FF  (
            .Q (\i2s_u/shift_reg_l [13] ),
            .CE (\CLMA_106_129/ntCECO ),
            .CK (ntclkbufg_0),
            .D (\i2s_u/shift_reg_l [12] ),
            .SR (ntR7));
	// ../source/i2s_top.v:52

    V_FFASYN /* i2s_u/shift_reg_l[20]/opit_0_inv/FF3/FF */ #(
            .GRS_EN("TRUE"), 
            .SET_RESET("RESET"), 
            .LRS_EN("TRUE"), 
            .INIT(1'b0))
        \CLMA_106_129/FF3/FF  (
            .Q (\i2s_u/shift_reg_l [20] ),
            .CE (\CLMA_106_129/ntCECO ),
            .CK (ntclkbufg_0),
            .D (\i2s_u/shift_reg_l [19] ),
            .SR (ntR7));
	// ../source/i2s_top.v:52

    V_LUT5CARRY /* N5_0_9/gateop_A2/FYA/V_FY */ #(
            .INIT(32'b10011001100110010011001100110011), 
            .ID_TO_LUT("FALSE"), 
            .CIN_TO_LUT("TRUE"), 
            .I4_TO_CARRY("TRUE"), 
            .I4_TO_LUT("FALSE"))
        \CLMA_106_129/FYA/V_FY  (
            .COUT (\CLMA_106_129/ntCYA ),
            .S (N13[9]),
            .CIN (_N145),
            .I0 (1'b0),
            .I1 (mic_data[21]),
            .I2 (1'b0),
            .I3 (1'b0),
            .I4 (ntR13),
            .ID (1'b0));
	// LUT = ~I1^CIN ;
	// CARRY = (~I1) ? CIN : (I4) ;
	// ../source/top.v:15

    V_LUT5CARRY /* N5_0_9/gateop_A2/FYB/V_FY */ #(
            .INIT(32'b10011001100110010011001100110011), 
            .ID_TO_LUT("FALSE"), 
            .CIN_TO_LUT("TRUE"), 
            .I4_TO_CARRY("TRUE"), 
            .I4_TO_LUT("FALSE"))
        \CLMA_106_129/FYB/V_FY  (
            .COUT (\CLMA_106_129/ntCYB ),
            .S (N13[10]),
            .CIN (\CLMA_106_129/ntCYA ),
            .I0 (1'b0),
            .I1 (mic_data[22]),
            .I2 (1'b0),
            .I3 (1'b0),
            .I4 (ntR13),
            .ID (1'b0));
	// LUT = ~I1^CIN ;
	// CARRY = (~I1) ? CIN : (I4) ;
	// ../source/top.v:15

    V_LUT5CARRY /* N5_0_11/gateop/FYC/V_FY */ #(
            .INIT(32'b01100110011001101100110011001100), 
            .ID_TO_LUT("FALSE"), 
            .CIN_TO_LUT("TRUE"), 
            .I4_TO_CARRY("TRUE"), 
            .I4_TO_LUT("FALSE"))
        \CLMA_106_129/FYC/V_FY  (
            .COUT (),
            .S (N13[11]),
            .CIN (\CLMA_106_129/ntCYB ),
            .I0 (1'b0),
            .I1 (mic_data[23]),
            .I2 (1'b0),
            .I3 (1'b0),
            .I4 (ntR10),
            .ID (1'b0));
	// LUT = I1^CIN ;
	// CARRY = (I1) ? CIN : (I4) ;
	// ../source/top.v:15

    V_LUT5 /* i2s_u/N342_1_4/gateop_perm/FYD/FYC */ #(
            .INIT(32'b00000000010100000000000001000000))
        \CLMA_106_129/FYD/FYC  (
            .Y (\i2s_u/N342 ),
            .I0 (\i2s_u/ws_cnt [10] ),
            .I1 (\i2s_u/_N189 ),
            .I2 (\i2s_u/ws_cnt [0] ),
            .I3 (\i2s_u/ws_cnt [1] ),
            .I4 (\i2s_u/_N190 ));
	// LUT = (~I0&I2&~I3&I4)|(~I0&I1&I2&~I3) ;

    V_INV \CLMA_106_129/LRSPOLMUX/V_INV  (
            .Z (\CLMA_106_129/ntRS_P ),
            .I (nt_rst_n));
	// ../source/i2s_top.v:52

    V_BUF \CLMA_106_129/RSMUX/V_BUF  (
            .Z (ntR7),
            .I (\CLMA_106_129/ntRS_P ));
	// ../source/i2s_top.v:52

    V_LUT5 /* i2s_u/N342_89/gateop_perm/FYA/FY */ #(
            .INIT(32'b01100000100000000000000100000110))
        \CLMA_106_132/FYA/FY  (
            .Y (\i2s_u/_N176 ),
            .I0 (\i2s_u/ws_cnt [2] ),
            .I1 (\i2s_u/ws_cnt [5] ),
            .I2 (\i2s_u/ws_cnt [7] ),
            .I3 (\i2s_u/ws_cnt [8] ),
            .I4 (\i2s_u/ws_cnt [3] ));
	// LUT = (I0&~I1&~I2&~I3&~I4)|(~I0&I1&~I2&~I3&~I4)|(~I0&~I1&~I2&I3&~I4)|(I0&I1&I2&~I3&I4)|(I0&~I1&I2&I3&I4)|(~I0&I1&I2&I3&I4) ;

    V_BUF \CLMA_106_133/CEMUX/V_BUF  (
            .Z (\CLMA_106_133/ntCECO ),
            .I (1'b1));
	// ../source/i2s_top.v:38

    V_FFASYN /* i2s_u/ws_cnt[0]/opit_0_inv_L5Q_perm/FF1/FF */ #(
            .GRS_EN("TRUE"), 
            .SET_RESET("RESET"), 
            .LRS_EN("TRUE"), 
            .INIT(1'b0))
        \CLMA_106_133/FF1/FF  (
            .Q (\i2s_u/ws_cnt [0] ),
            .CE (\CLMA_106_133/ntCECO ),
            .CK (ntclkbufg_0),
            .D (\CLMA_106_133/ntY1 ),
            .SR (ntR6));
	// ../source/i2s_top.v:38

    V_LUT5 /* i2s_u/N342_112/gateop_perm/FYA/FY */ #(
            .INIT(32'b00000000110011000011001100000000))
        \CLMA_106_133/FYA/FY  (
            .Y (\i2s_u/_N260 ),
            .I0 (1'b0),
            .I1 (\i2s_u/ws_cnt [2] ),
            .I2 (1'b0),
            .I3 (\i2s_u/ws_cnt [3] ),
            .I4 (\i2s_u/ws_cnt [5] ));
	// LUT = (~I1&I3&~I4)|(I1&~I3&I4) ;

    V_LUT5 /* i2s_u/ws_cnt[0]/opit_0_inv_L5Q_perm/FYB/FYC */ #(
            .INIT(32'b00000000000000001111111111111111))
        \CLMA_106_133/FYB/FYC  (
            .Y (\CLMA_106_133/ntY1 ),
            .I0 (1'b0),
            .I1 (1'b0),
            .I2 (1'b0),
            .I3 (1'b0),
            .I4 (\i2s_u/ws_cnt [0] ));
	// LUT = ~I4 ;
	// ../source/i2s_top.v:38

    V_LUT5 /* i2s_u/N342_67/gateop_perm/FYC/FY */ #(
            .INIT(32'b00001000001000000001000001000000))
        \CLMA_106_133/FYC/FY  (
            .Y (\i2s_u/_N215 ),
            .I0 (\i2s_u/ws_cnt [7] ),
            .I1 (\i2s_u/ws_cnt [5] ),
            .I2 (\i2s_u/ws_cnt [3] ),
            .I3 (\i2s_u/ws_cnt [8] ),
            .I4 (\i2s_u/ws_cnt [4] ));
	// LUT = (~I0&I1&I2&~I3&~I4)|(~I0&~I1&I2&I3&~I4)|(I0&~I1&I2&~I3&I4)|(I0&I1&~I2&I3&I4) ;

    V_LUT5 /* i2s_u/N342_79/gateop_perm/FYD/FYC */ #(
            .INIT(32'b00000110000010000000000000010000))
        \CLMA_106_133/FYD/FYC  (
            .Y (\i2s_u/_N227 ),
            .I0 (\i2s_u/ws_cnt [5] ),
            .I1 (\i2s_u/ws_cnt [2] ),
            .I2 (\i2s_u/ws_cnt [7] ),
            .I3 (\i2s_u/ws_cnt [8] ),
            .I4 (\i2s_u/ws_cnt [3] ));
	// LUT = (~I0&~I1&I2&~I3&~I4)|(I0&I1&~I2&~I3&I4)|(I0&~I1&~I2&I3&I4)|(~I0&I1&~I2&I3&I4) ;

    V_BUF \CLMA_106_133/RSMUX/V_BUF  (
            .Z (ntR6),
            .I (ntR7));
	// ../source/i2s_top.v:38

    V_BUF \CLMA_106_136/CEMUX/V_BUF  (
            .Z (\CLMA_106_136/ntCECO ),
            .I (\i2s_u/ready ));
	// ../source/i2s_top.v:114

    V_FFASYN /* i2s_u/ldata[21]/opit_0_inv/FF0/FF */ #(
            .GRS_EN("TRUE"), 
            .SET_RESET("RESET"), 
            .LRS_EN("TRUE"), 
            .INIT(1'b0))
        \CLMA_106_136/FF0/FF  (
            .Q (mic_data[21]),
            .CE (\CLMA_106_136/ntCECO ),
            .CK (ntclkbufg_0),
            .D (\i2s_u/shift_reg_l [21] ),
            .SR (\CLMA_106_136/ntRSCO ));
	// ../source/i2s_top.v:114

    V_FFASYN /* i2s_u/ldata[20]/opit_0_inv/FF1/FF */ #(
            .GRS_EN("TRUE"), 
            .SET_RESET("RESET"), 
            .LRS_EN("TRUE"), 
            .INIT(1'b0))
        \CLMA_106_136/FF1/FF  (
            .Q (mic_data[20]),
            .CE (\CLMA_106_136/ntCECO ),
            .CK (ntclkbufg_0),
            .D (\i2s_u/shift_reg_l [20] ),
            .SR (\CLMA_106_136/ntRSCO ));
	// ../source/i2s_top.v:114

    V_FFASYN /* i2s_u/ldata[19]/opit_0_inv/FF2/FF */ #(
            .GRS_EN("TRUE"), 
            .SET_RESET("RESET"), 
            .LRS_EN("TRUE"), 
            .INIT(1'b0))
        \CLMA_106_136/FF2/FF  (
            .Q (mic_data[19]),
            .CE (\CLMA_106_136/ntCECO ),
            .CK (ntclkbufg_0),
            .D (\i2s_u/shift_reg_l [19] ),
            .SR (\CLMA_106_136/ntRSCO ));
	// ../source/i2s_top.v:114

    V_FFASYN /* i2s_u/ldata[23]/opit_0_inv/FF3/FF */ #(
            .GRS_EN("TRUE"), 
            .SET_RESET("RESET"), 
            .LRS_EN("TRUE"), 
            .INIT(1'b0))
        \CLMA_106_136/FF3/FF  (
            .Q (mic_data[23]),
            .CE (\CLMA_106_136/ntCECO ),
            .CK (ntclkbufg_0),
            .D (\i2s_u/shift_reg_l [23] ),
            .SR (\CLMA_106_136/ntRSCO ));
	// ../source/i2s_top.v:114

    V_FFASYN /* i2s_u/ldata[22]/opit_0_inv/FFCD/FF */ #(
            .GRS_EN("TRUE"), 
            .SET_RESET("RESET"), 
            .LRS_EN("TRUE"), 
            .INIT(1'b0))
        \CLMA_106_136/FFCD/FF  (
            .Q (mic_data[22]),
            .CE (\CLMA_106_136/ntCECO ),
            .CK (ntclkbufg_0),
            .D (\i2s_u/shift_reg_l [22] ),
            .SR (\CLMA_106_136/ntRSCO ));
	// ../source/i2s_top.v:114

    V_LUT5 /* i2s_u/N7_mux10/gateop_perm/FYA/FY */ #(
            .INIT(32'b11101110101010101010101010101010))
        \CLMA_106_136/FYA/FY  (
            .Y (nt_mic_ws),
            .I0 (\i2s_u/ws_cnt [10] ),
            .I1 (\i2s_u/ws_cnt [8] ),
            .I2 (1'b0),
            .I3 (\i2s_u/ws_cnt [9] ),
            .I4 (\i2s_u/ws_cnt [7] ));
	// LUT = (I1&I3&I4)|(I0) ;

    V_INV \CLMA_106_136/LRSPOLMUX/V_INV  (
            .Z (\CLMA_106_136/ntRS_P ),
            .I (nt_rst_n));
	// ../source/i2s_top.v:114

    V_BUF \CLMA_106_136/RSMUX/V_BUF  (
            .Z (\CLMA_106_136/ntRSCO ),
            .I (\CLMA_106_136/ntRS_P ));
	// ../source/i2s_top.v:114

    V_BUF \CLMA_106_137/CEMUX/V_BUF  (
            .Z (\CLMA_106_137/ntCECO ),
            .I (1'b1));
	// ../source/i2s_top.v:38

    V_FFASYN /* i2s_u/ws_cnt[1]/opit_0_inv_A2Q20/FF0/FF */ #(
            .GRS_EN("TRUE"), 
            .SET_RESET("RESET"), 
            .LRS_EN("TRUE"), 
            .INIT(1'b0))
        \CLMA_106_137/FF0/FF  (
            .Q (\i2s_u/ws_cnt [1] ),
            .CE (\CLMA_106_137/ntCECO ),
            .CK (ntclkbufg_0),
            .D (\CLMA_106_137/ntY0 ),
            .SR (ntR5));
	// ../source/i2s_top.v:38

    V_FFASYN /* i2s_u/ws_cnt[1]/opit_0_inv_A2Q20/FF1/FF */ #(
            .GRS_EN("TRUE"), 
            .SET_RESET("RESET"), 
            .LRS_EN("TRUE"), 
            .INIT(1'b0))
        \CLMA_106_137/FF1/FF  (
            .Q (\i2s_u/ws_cnt [2] ),
            .CE (\CLMA_106_137/ntCECO ),
            .CK (ntclkbufg_0),
            .D (\CLMA_106_137/ntY1 ),
            .SR (ntR5));
	// ../source/i2s_top.v:38

    V_FFASYN /* i2s_u/ws_cnt[4]/opit_0_inv_A2Q21/FF2/FF */ #(
            .GRS_EN("TRUE"), 
            .SET_RESET("RESET"), 
            .LRS_EN("TRUE"), 
            .INIT(1'b0))
        \CLMA_106_137/FF2/FF  (
            .Q (\i2s_u/ws_cnt [3] ),
            .CE (\CLMA_106_137/ntCECO ),
            .CK (ntclkbufg_0),
            .D (\CLMA_106_137/ntY2 ),
            .SR (ntR5));
	// ../source/i2s_top.v:38

    V_FFASYN /* i2s_u/ws_cnt[4]/opit_0_inv_A2Q21/FF3/FF */ #(
            .GRS_EN("TRUE"), 
            .SET_RESET("RESET"), 
            .LRS_EN("TRUE"), 
            .INIT(1'b0))
        \CLMA_106_137/FF3/FF  (
            .Q (\i2s_u/ws_cnt [4] ),
            .CE (\CLMA_106_137/ntCECO ),
            .CK (ntclkbufg_0),
            .D (\CLMA_106_137/ntY3 ),
            .SR (ntR5));
	// ../source/i2s_top.v:38

    V_LUT5CARRY /* i2s_u/ws_cnt[1]/opit_0_inv_A2Q20/FYA/V_FY */ #(
            .INIT(32'b01100110011001100000000000000000), 
            .ID_TO_LUT("FALSE"), 
            .CIN_TO_LUT("FALSE"), 
            .I4_TO_CARRY("TRUE"), 
            .I4_TO_LUT("FALSE"))
        \CLMA_106_137/FYA/V_FY  (
            .COUT (\CLMA_106_137/ntCYA ),
            .S (\CLMA_106_137/ntY0 ),
            .CIN (1'b0),
            .I0 (\i2s_u/ws_cnt [0] ),
            .I1 (\i2s_u/ws_cnt [1] ),
            .I2 (1'b0),
            .I3 (1'b0),
            .I4 (ntR13),
            .ID (1'b0));
	// LUT = I1^I0 ;
	// CARRY = (1'b0) ? CIN : (I4) ;
	// ../source/i2s_top.v:38

    V_LUT5CARRY /* i2s_u/ws_cnt[1]/opit_0_inv_A2Q20/FYB/V_FY */ #(
            .INIT(32'b01111000011110001000000010000000), 
            .ID_TO_LUT("FALSE"), 
            .CIN_TO_LUT("FALSE"), 
            .I4_TO_CARRY("TRUE"), 
            .I4_TO_LUT("FALSE"))
        \CLMA_106_137/FYB/V_FY  (
            .COUT (\CLMA_106_137/ntCYB ),
            .S (\CLMA_106_137/ntY1 ),
            .CIN (\CLMA_106_137/ntCYA ),
            .I0 (\i2s_u/ws_cnt [0] ),
            .I1 (\i2s_u/ws_cnt [1] ),
            .I2 (\i2s_u/ws_cnt [2] ),
            .I3 (1'b0),
            .I4 (ntR10),
            .ID (1'b0));
	// LUT = (I0&I1&~I2)|(~I1&I2)|(~I0&I2) ;
	// CARRY = (I0&I1&I2) ? CIN : (I4) ;
	// ../source/i2s_top.v:38

    V_LUT5CARRY /* i2s_u/ws_cnt[4]/opit_0_inv_A2Q21/FYC/V_FY */ #(
            .INIT(32'b01100110011001101100110011001100), 
            .ID_TO_LUT("FALSE"), 
            .CIN_TO_LUT("TRUE"), 
            .I4_TO_CARRY("TRUE"), 
            .I4_TO_LUT("FALSE"))
        \CLMA_106_137/FYC/V_FY  (
            .COUT (\CLMA_106_137/ntCYC ),
            .S (\CLMA_106_137/ntY2 ),
            .CIN (\CLMA_106_137/ntCYB ),
            .I0 (1'b0),
            .I1 (\i2s_u/ws_cnt [3] ),
            .I2 (1'b0),
            .I3 (1'b0),
            .I4 (ntR10),
            .ID (1'b0));
	// LUT = I1^CIN ;
	// CARRY = (I1) ? CIN : (I4) ;
	// ../source/i2s_top.v:38

    V_LUT5CARRY /* i2s_u/ws_cnt[4]/opit_0_inv_A2Q21/FYD/V_FY */ #(
            .INIT(32'b01100110011001101100110011001100), 
            .ID_TO_LUT("FALSE"), 
            .CIN_TO_LUT("TRUE"), 
            .I4_TO_CARRY("TRUE"), 
            .I4_TO_LUT("FALSE"))
        \CLMA_106_137/FYD/V_FY  (
            .COUT (\i2s_u/_N118 ),
            .S (\CLMA_106_137/ntY3 ),
            .CIN (\CLMA_106_137/ntCYC ),
            .I0 (1'b0),
            .I1 (\i2s_u/ws_cnt [4] ),
            .I2 (1'b0),
            .I3 (1'b0),
            .I4 (ntR10),
            .ID (1'b0));
	// LUT = I1^CIN ;
	// CARRY = (I1) ? CIN : (I4) ;
	// ../source/i2s_top.v:38

    V_BUF \CLMA_106_137/RSMUX/V_BUF  (
            .Z (ntR5),
            .I (ntR6));
	// ../source/i2s_top.v:38

    V_BUF \CLMA_106_141/CEMUX/V_BUF  (
            .Z (\CLMA_106_141/ntCECO ),
            .I (1'b1));
	// ../source/i2s_top.v:38

    V_FFASYN /* i2s_u/ws_cnt[6]/opit_0_inv_A2Q21/FF0/FF */ #(
            .GRS_EN("TRUE"), 
            .SET_RESET("RESET"), 
            .LRS_EN("TRUE"), 
            .INIT(1'b0))
        \CLMA_106_141/FF0/FF  (
            .Q (\i2s_u/ws_cnt [5] ),
            .CE (\CLMA_106_141/ntCECO ),
            .CK (ntclkbufg_0),
            .D (\CLMA_106_141/ntY0 ),
            .SR (ntR4));
	// ../source/i2s_top.v:38

    V_FFASYN /* i2s_u/ws_cnt[6]/opit_0_inv_A2Q21/FF1/FF */ #(
            .GRS_EN("TRUE"), 
            .SET_RESET("RESET"), 
            .LRS_EN("TRUE"), 
            .INIT(1'b0))
        \CLMA_106_141/FF1/FF  (
            .Q (\i2s_u/ws_cnt [6] ),
            .CE (\CLMA_106_141/ntCECO ),
            .CK (ntclkbufg_0),
            .D (\CLMA_106_141/ntY1 ),
            .SR (ntR4));
	// ../source/i2s_top.v:38

    V_FFASYN /* i2s_u/ws_cnt[8]/opit_0_inv_A2Q21/FF2/FF */ #(
            .GRS_EN("TRUE"), 
            .SET_RESET("RESET"), 
            .LRS_EN("TRUE"), 
            .INIT(1'b0))
        \CLMA_106_141/FF2/FF  (
            .Q (\i2s_u/ws_cnt [7] ),
            .CE (\CLMA_106_141/ntCECO ),
            .CK (ntclkbufg_0),
            .D (\CLMA_106_141/ntY2 ),
            .SR (ntR4));
	// ../source/i2s_top.v:38

    V_FFASYN /* i2s_u/ws_cnt[8]/opit_0_inv_A2Q21/FF3/FF */ #(
            .GRS_EN("TRUE"), 
            .SET_RESET("RESET"), 
            .LRS_EN("TRUE"), 
            .INIT(1'b0))
        \CLMA_106_141/FF3/FF  (
            .Q (\i2s_u/ws_cnt [8] ),
            .CE (\CLMA_106_141/ntCECO ),
            .CK (ntclkbufg_0),
            .D (\CLMA_106_141/ntY3 ),
            .SR (ntR4));
	// ../source/i2s_top.v:38

    V_LUT5CARRY /* i2s_u/ws_cnt[6]/opit_0_inv_A2Q21/FYA/V_FY */ #(
            .INIT(32'b01100110011001101100110011001100), 
            .ID_TO_LUT("FALSE"), 
            .CIN_TO_LUT("TRUE"), 
            .I4_TO_CARRY("TRUE"), 
            .I4_TO_LUT("FALSE"))
        \CLMA_106_141/FYA/V_FY  (
            .COUT (\CLMA_106_141/ntCYA ),
            .S (\CLMA_106_141/ntY0 ),
            .CIN (\i2s_u/_N118 ),
            .I0 (1'b0),
            .I1 (\i2s_u/ws_cnt [5] ),
            .I2 (1'b0),
            .I3 (1'b0),
            .I4 (ntR10),
            .ID (1'b0));
	// LUT = I1^CIN ;
	// CARRY = (I1) ? CIN : (I4) ;
	// ../source/i2s_top.v:38

    V_LUT5CARRY /* i2s_u/ws_cnt[6]/opit_0_inv_A2Q21/FYB/V_FY */ #(
            .INIT(32'b01100110011001101100110011001100), 
            .ID_TO_LUT("FALSE"), 
            .CIN_TO_LUT("TRUE"), 
            .I4_TO_CARRY("TRUE"), 
            .I4_TO_LUT("FALSE"))
        \CLMA_106_141/FYB/V_FY  (
            .COUT (\CLMA_106_141/ntCYB ),
            .S (\CLMA_106_141/ntY1 ),
            .CIN (\CLMA_106_141/ntCYA ),
            .I0 (1'b0),
            .I1 (\i2s_u/ws_cnt [6] ),
            .I2 (1'b0),
            .I3 (1'b0),
            .I4 (ntR10),
            .ID (1'b0));
	// LUT = I1^CIN ;
	// CARRY = (I1) ? CIN : (I4) ;
	// ../source/i2s_top.v:38

    V_LUT5CARRY /* i2s_u/ws_cnt[8]/opit_0_inv_A2Q21/FYC/V_FY */ #(
            .INIT(32'b01100110011001101100110011001100), 
            .ID_TO_LUT("FALSE"), 
            .CIN_TO_LUT("TRUE"), 
            .I4_TO_CARRY("TRUE"), 
            .I4_TO_LUT("FALSE"))
        \CLMA_106_141/FYC/V_FY  (
            .COUT (\CLMA_106_141/ntCYC ),
            .S (\CLMA_106_141/ntY2 ),
            .CIN (\CLMA_106_141/ntCYB ),
            .I0 (1'b0),
            .I1 (\i2s_u/ws_cnt [7] ),
            .I2 (1'b0),
            .I3 (1'b0),
            .I4 (ntR10),
            .ID (1'b0));
	// LUT = I1^CIN ;
	// CARRY = (I1) ? CIN : (I4) ;
	// ../source/i2s_top.v:38

    V_LUT5CARRY /* i2s_u/ws_cnt[8]/opit_0_inv_A2Q21/FYD/V_FY */ #(
            .INIT(32'b01100000011000001100110011001100), 
            .ID_TO_LUT("FALSE"), 
            .CIN_TO_LUT("TRUE"), 
            .I4_TO_CARRY("TRUE"), 
            .I4_TO_LUT("FALSE"))
        \CLMA_106_141/FYD/V_FY  (
            .COUT (\i2s_u/_N122 ),
            .S (\CLMA_106_141/ntY3 ),
            .CIN (\CLMA_106_141/ntCYC ),
            .I0 (1'b0),
            .I1 (\i2s_u/ws_cnt [8] ),
            .I2 (\i2s_u/N226_inv ),
            .I3 (1'b0),
            .I4 (ntR10),
            .ID (1'b0));
	// LUT = (CIN&~I1&I2)|(~CIN&I1&I2) ;
	// CARRY = (I1) ? CIN : (I4) ;
	// ../source/i2s_top.v:38

    V_BUF \CLMA_106_141/RSMUX/V_BUF  (
            .Z (ntR4),
            .I (ntR5));
	// ../source/i2s_top.v:38

    V_BUF \CLMA_106_145/CEMUX/V_BUF  (
            .Z (\CLMA_106_145/ntCECO ),
            .I (1'b1));
	// ../source/i2s_top.v:38

    V_FFASYN /* i2s_u/ws_cnt[10]/opit_0_inv_A2Q21/FF0/FF */ #(
            .GRS_EN("TRUE"), 
            .SET_RESET("RESET"), 
            .LRS_EN("TRUE"), 
            .INIT(1'b0))
        \CLMA_106_145/FF0/FF  (
            .Q (\i2s_u/ws_cnt [9] ),
            .CE (\CLMA_106_145/ntCECO ),
            .CK (ntclkbufg_0),
            .D (\CLMA_106_145/ntY0 ),
            .SR (\CLMA_106_145/ntRSCO ));
	// ../source/i2s_top.v:38

    V_FFASYN /* i2s_u/ws_cnt[10]/opit_0_inv_A2Q21/FF1/FF */ #(
            .GRS_EN("TRUE"), 
            .SET_RESET("RESET"), 
            .LRS_EN("TRUE"), 
            .INIT(1'b0))
        \CLMA_106_145/FF1/FF  (
            .Q (\i2s_u/ws_cnt [10] ),
            .CE (\CLMA_106_145/ntCECO ),
            .CK (ntclkbufg_0),
            .D (\CLMA_106_145/ntY1 ),
            .SR (\CLMA_106_145/ntRSCO ));
	// ../source/i2s_top.v:38

    V_LUT5CARRY /* i2s_u/ws_cnt[10]/opit_0_inv_A2Q21/FYA/V_FY */ #(
            .INIT(32'b01100000011000001100110011001100), 
            .ID_TO_LUT("FALSE"), 
            .CIN_TO_LUT("TRUE"), 
            .I4_TO_CARRY("TRUE"), 
            .I4_TO_LUT("FALSE"))
        \CLMA_106_145/FYA/V_FY  (
            .COUT (\CLMA_106_145/ntCYA ),
            .S (\CLMA_106_145/ntY0 ),
            .CIN (\i2s_u/_N122 ),
            .I0 (1'b0),
            .I1 (\i2s_u/ws_cnt [9] ),
            .I2 (\i2s_u/N226_inv ),
            .I3 (1'b0),
            .I4 (ntR10),
            .ID (1'b0));
	// LUT = (CIN&~I1&I2)|(~CIN&I1&I2) ;
	// CARRY = (I1) ? CIN : (I4) ;
	// ../source/i2s_top.v:38

    V_LUT5CARRY /* i2s_u/ws_cnt[10]/opit_0_inv_A2Q21/FYB/V_FY */ #(
            .INIT(32'b01100000011000001100110011001100), 
            .ID_TO_LUT("FALSE"), 
            .CIN_TO_LUT("TRUE"), 
            .I4_TO_CARRY("TRUE"), 
            .I4_TO_LUT("FALSE"))
        \CLMA_106_145/FYB/V_FY  (
            .COUT (),
            .S (\CLMA_106_145/ntY1 ),
            .CIN (\CLMA_106_145/ntCYA ),
            .I0 (1'b0),
            .I1 (\i2s_u/ws_cnt [10] ),
            .I2 (\i2s_u/N226_inv ),
            .I3 (1'b0),
            .I4 (ntR10),
            .ID (1'b0));
	// LUT = (CIN&~I1&I2)|(~CIN&I1&I2) ;
	// CARRY = (I1) ? CIN : (I4) ;
	// ../source/i2s_top.v:38

    V_LUT5 /* i2s_u/N7_mux9_1/gateop/FYC/FY */ #(
            .INIT(32'b00100010001000100010001000100010))
        \CLMA_106_145/FYC/FY  (
            .Y (\i2s_u/_N347 ),
            .I0 (\i2s_u/ws_cnt [9] ),
            .I1 (\i2s_u/ws_cnt [8] ),
            .I2 (1'b0),
            .I3 (1'b0),
            .I4 (1'b0));
	// LUT = I0&~I1 ;

    V_LUT5 /* i2s_u/N342_197/gateop_perm/FYD/FYC */ #(
            .INIT(32'b10001000100010000000000000000000))
        \CLMA_106_145/FYD/FYC  (
            .Y (\i2s_u/_N346 ),
            .I0 (\i2s_u/ws_cnt [2] ),
            .I1 (\i2s_u/ws_cnt [3] ),
            .I2 (1'b0),
            .I3 (1'b0),
            .I4 (\i2s_u/ws_cnt [5] ));
	// LUT = I0&I1&I4 ;

    V_BUF \CLMA_106_145/RSMUX/V_BUF  (
            .Z (\CLMA_106_145/ntRSCO ),
            .I (ntR4));
	// ../source/i2s_top.v:38

    V_BUF \CLMA_114_100/CEMUX/V_BUF  (
            .Z (\CLMA_114_100/ntCECO ),
            .I (1'b1));
	// ../source/i2s_top.v:24

    V_FFASYN /* i2s_u/sck_cnt[0]/opit_0_inv_L5Q_perm/FF0/FF */ #(
            .GRS_EN("TRUE"), 
            .SET_RESET("RESET"), 
            .LRS_EN("TRUE"), 
            .INIT(1'b0))
        \CLMA_114_100/FF0/FF  (
            .Q (\i2s_u/sck_cnt [0] ),
            .CE (\CLMA_114_100/ntCECO ),
            .CK (ntclkbufg_0),
            .D (\CLMA_114_100/ntY0 ),
            .SR (\CLMA_114_100/ntRSCO ));
	// ../source/i2s_top.v:24

    V_LUT5 /* i2s_u/sck_cnt[0]/opit_0_inv_L5Q_perm/FYA/FY */ #(
            .INIT(32'b00000000000000001111111111111111))
        \CLMA_114_100/FYA/FY  (
            .Y (\CLMA_114_100/ntY0 ),
            .I0 (1'b0),
            .I1 (1'b0),
            .I2 (1'b0),
            .I3 (1'b0),
            .I4 (\i2s_u/sck_cnt [0] ));
	// LUT = ~I4 ;
	// ../source/i2s_top.v:24

    V_INV \CLMA_114_100/LRSPOLMUX/V_INV  (
            .Z (\CLMA_114_100/ntRS_P ),
            .I (nt_rst_n));
	// ../source/i2s_top.v:24

    V_BUF \CLMA_114_100/RSMUX/V_BUF  (
            .Z (\CLMA_114_100/ntRSCO ),
            .I (\CLMA_114_100/ntRS_P ));
	// ../source/i2s_top.v:24

    V_LUT5 /* GND_0/FYA/FY */ #(
            .INIT(32'b00000000000000000000000000000000))
        \CLMA_114_112/FYA/FY  (
            .Y (ntR9),
            .I0 (1'b0),
            .I1 (1'b0),
            .I2 (1'b0),
            .I3 (1'b0),
            .I4 (1'b0));
	// LUT = 1'b0 ;

    V_LUT5 /* VCC_1/FYB/FYC */ #(
            .INIT(32'b11111111111111111111111111111111))
        \CLMA_114_112/FYB/FYC  (
            .Y (ntR12),
            .I0 (1'b0),
            .I1 (1'b0),
            .I2 (1'b0),
            .I3 (1'b0),
            .I4 (1'b0));
	// LUT = 1'b1 ;

    V_LUT5 /* i2s_u/N342_115/gateop_perm/FYA/FY */ #(
            .INIT(32'b00100000000001001000000100010000))
        \CLMA_114_132/FYA/FY  (
            .Y (\i2s_u/_N196 ),
            .I0 (\i2s_u/ws_cnt [3] ),
            .I1 (\i2s_u/ws_cnt [7] ),
            .I2 (\i2s_u/ws_cnt [2] ),
            .I3 (\i2s_u/ws_cnt [5] ),
            .I4 (\i2s_u/ws_cnt [4] ));
	// LUT = (~I0&~I1&I2&~I3&~I4)|(~I0&~I1&~I2&I3&~I4)|(I0&I1&I2&I3&~I4)|(~I0&I1&~I2&~I3&I4)|(I0&~I1&I2&I3&I4) ;

    V_LUT5 /* i2s_u/N342_488/gateop_perm/FYA/FY */ #(
            .INIT(32'b00100000000000000000000000000000))
        \CLMA_114_136/FYA/FY  (
            .Y (\i2s_u/_N354 ),
            .I0 (\i2s_u/ws_cnt [10] ),
            .I1 (\i2s_u/ws_cnt [8] ),
            .I2 (\i2s_u/ws_cnt [9] ),
            .I3 (\i2s_u/ws_cnt [1] ),
            .I4 (\i2s_u/_N346 ));
	// LUT = I0&~I1&I2&I3&I4 ;

    V_LUT5 /* i2s_u/N226_inv/gateop_perm/FYB/FYC */ #(
            .INIT(32'b01111111111111111111111111111111))
        \CLMA_114_136/FYB/FYC  (
            .Y (\i2s_u/N226_inv ),
            .I0 (\i2s_u/ws_cnt [4] ),
            .I1 (\i2s_u/ws_cnt [7] ),
            .I2 (\i2s_u/ws_cnt [0] ),
            .I3 (\i2s_u/ws_cnt [6] ),
            .I4 (\i2s_u/_N354 ));
	// LUT = (~I4)|(~I3)|(~I2)|(~I1)|(~I0) ;

    V_LUT5 /* i2s_u/N285_4/gateop_perm/FYC/FY */ #(
            .INIT(32'b00000000000000000000000000000010))
        \CLMA_114_136/FYC/FY  (
            .Y (\i2s_u/ready ),
            .I0 (\i2s_u/_N354 ),
            .I1 (\i2s_u/ws_cnt [4] ),
            .I2 (\i2s_u/ws_cnt [7] ),
            .I3 (\i2s_u/ws_cnt [6] ),
            .I4 (\i2s_u/ws_cnt [0] ));
	// LUT = I0&~I1&~I2&~I3&~I4 ;

    V_LUT5 /* GND_1/FYA/FY */ #(
            .INIT(32'b00000000000000000000000000000000))
        \CLMA_114_148/FYA/FY  (
            .Y (ntR10),
            .I0 (1'b0),
            .I1 (1'b0),
            .I2 (1'b0),
            .I3 (1'b0),
            .I4 (1'b0));
	// LUT = 1'b0 ;

    V_LUT5 /* VCC_0/FYB/FYC */ #(
            .INIT(32'b11111111111111111111111111111111))
        \CLMA_114_148/FYB/FYC  (
            .Y (ntR13),
            .I0 (1'b0),
            .I1 (1'b0),
            .I2 (1'b0),
            .I3 (1'b0),
            .I4 (1'b0));
	// LUT = 1'b1 ;

    V_LUT5CARRY /* dac_u/N9.lt_0/gateop_A2/FYA/V_FYS */ #(
            .INIT(32'b01111111000001110000000000000000), 
            .ID_TO_LUT("FALSE"), 
            .CIN_TO_LUT("FALSE"), 
            .I4_TO_CARRY("FALSE"), 
            .I4_TO_LUT("FALSE"))
        \CLMS_102_125/FYA/V_FYS  (
            .COUT (\CLMS_102_125/ntCYA ),
            .S (),
            .CIN (1'b0),
            .I0 (\dac_u/count [0] ),
            .I1 (mic_data[12]),
            .I2 (\dac_u/count [1] ),
            .I3 (N13[1]),
            .I4 (1'b0),
            .ID (1'b0));
	// LUT = (~I2&I3)|(~I1&I3)|(~I0&I3)|(~I1&~I2)|(~I0&~I2) ;
	// CARRY = (1'b0) ? CIN : ((~I2&I3)|(~I1&I3)|(~I0&I3)|(~I1&~I2)|(~I0&~I2)) ;
	// ../source/dac_out.v:20

    V_LUT5CARRY /* dac_u/N9.lt_0/gateop_A2/FYB/V_FYSC */ #(
            .INIT(32'b11011111000011011001000000001001), 
            .ID_TO_LUT("FALSE"), 
            .CIN_TO_LUT("FALSE"), 
            .I4_TO_CARRY("FALSE"), 
            .I4_TO_LUT("FALSE"))
        \CLMS_102_125/FYB/V_FYSC  (
            .COUT (\CLMS_102_125/ntCYB ),
            .S (),
            .CIN (\CLMS_102_125/ntCYA ),
            .I0 (\dac_u/count [2] ),
            .I1 (N13[2]),
            .I2 (\dac_u/count [3] ),
            .I3 (N13[3]),
            .I4 (1'b0),
            .ID (1'b0));
	// LUT = (~I2&I3)|(I1&I3)|(~I0&I3)|(I1&~I2)|(~I0&~I2) ;
	// CARRY = ((~I0&~I1&~I2&~I3)|(I0&I1&~I2&~I3)|(~I0&~I1&I2&I3)|(I0&I1&I2&I3)) ? CIN : ((~I2&I3)|(I1&I3)|(~I0&I3)|(I1&~I2)|(~I0&~I2)) ;
	// ../source/dac_out.v:20

    V_LUT5CARRY /* dac_u/N9.lt_2/gateop_A2/FYC/V_FYS */ #(
            .INIT(32'b11011111000011011001000000001001), 
            .ID_TO_LUT("FALSE"), 
            .CIN_TO_LUT("FALSE"), 
            .I4_TO_CARRY("FALSE"), 
            .I4_TO_LUT("FALSE"))
        \CLMS_102_125/FYC/V_FYS  (
            .COUT (\CLMS_102_125/ntCYC ),
            .S (),
            .CIN (\CLMS_102_125/ntCYB ),
            .I0 (\dac_u/count [4] ),
            .I1 (N13[4]),
            .I2 (\dac_u/count [5] ),
            .I3 (N13[5]),
            .I4 (1'b0),
            .ID (1'b0));
	// LUT = (~I2&I3)|(I1&I3)|(~I0&I3)|(I1&~I2)|(~I0&~I2) ;
	// CARRY = ((~I0&~I1&~I2&~I3)|(I0&I1&~I2&~I3)|(~I0&~I1&I2&I3)|(I0&I1&I2&I3)) ? CIN : ((~I2&I3)|(I1&I3)|(~I0&I3)|(I1&~I2)|(~I0&~I2)) ;
	// ../source/dac_out.v:20

    V_LUT5CARRY /* dac_u/N9.lt_2/gateop_A2/FYD/V_FYSC */ #(
            .INIT(32'b11011111000011011001000000001001), 
            .ID_TO_LUT("FALSE"), 
            .CIN_TO_LUT("FALSE"), 
            .I4_TO_CARRY("FALSE"), 
            .I4_TO_LUT("FALSE"))
        \CLMS_102_125/FYD/V_FYSC  (
            .COUT (\dac_u/N9.co [6] ),
            .S (),
            .CIN (\CLMS_102_125/ntCYC ),
            .I0 (\dac_u/count [6] ),
            .I1 (N13[6]),
            .I2 (\dac_u/count [7] ),
            .I3 (N13[7]),
            .I4 (1'b0),
            .ID (1'b0));
	// LUT = (~I2&I3)|(I1&I3)|(~I0&I3)|(I1&~I2)|(~I0&~I2) ;
	// CARRY = ((~I0&~I1&~I2&~I3)|(I0&I1&~I2&~I3)|(~I0&~I1&I2&I3)|(I0&I1&I2&I3)) ? CIN : ((~I2&I3)|(I1&I3)|(~I0&I3)|(I1&~I2)|(~I0&~I2)) ;
	// ../source/dac_out.v:20

    V_BUF \CLMS_102_129/CEMUX/V_BUF  (
            .Z (\CLMS_102_129/ntCECO ),
            .I (\i2s_u/ready ));
	// ../source/i2s_top.v:114

    V_FFASYN /* i2s_u/ldata[16]/opit_0_inv/FF0/FF */ #(
            .GRS_EN("TRUE"), 
            .SET_RESET("RESET"), 
            .LRS_EN("TRUE"), 
            .INIT(1'b0))
        \CLMS_102_129/FF0/FF  (
            .Q (mic_data[16]),
            .CE (\CLMS_102_129/ntCECO ),
            .CK (ntclkbufg_0),
            .D (\i2s_u/shift_reg_l [16] ),
            .SR (\CLMS_102_129/ntRSCO ));
	// ../source/i2s_top.v:114

    V_FFASYN /* i2s_u/ldata[18]/opit_0_inv/FF1/FF */ #(
            .GRS_EN("TRUE"), 
            .SET_RESET("RESET"), 
            .LRS_EN("TRUE"), 
            .INIT(1'b0))
        \CLMS_102_129/FF1/FF  (
            .Q (mic_data[18]),
            .CE (\CLMS_102_129/ntCECO ),
            .CK (ntclkbufg_0),
            .D (\i2s_u/shift_reg_l [18] ),
            .SR (\CLMS_102_129/ntRSCO ));
	// ../source/i2s_top.v:114

    V_FFASYN /* i2s_u/ldata[17]/opit_0_inv/FF2/FF */ #(
            .GRS_EN("TRUE"), 
            .SET_RESET("RESET"), 
            .LRS_EN("TRUE"), 
            .INIT(1'b0))
        \CLMS_102_129/FF2/FF  (
            .Q (mic_data[17]),
            .CE (\CLMS_102_129/ntCECO ),
            .CK (ntclkbufg_0),
            .D (\i2s_u/shift_reg_l [17] ),
            .SR (\CLMS_102_129/ntRSCO ));
	// ../source/i2s_top.v:114

    V_FFASYN /* i2s_u/ldata[15]/opit_0_inv/FF3/FF */ #(
            .GRS_EN("TRUE"), 
            .SET_RESET("RESET"), 
            .LRS_EN("TRUE"), 
            .INIT(1'b0))
        \CLMS_102_129/FF3/FF  (
            .Q (mic_data[15]),
            .CE (\CLMS_102_129/ntCECO ),
            .CK (ntclkbufg_0),
            .D (\i2s_u/shift_reg_l [15] ),
            .SR (\CLMS_102_129/ntRSCO ));
	// ../source/i2s_top.v:114

    V_FFASYN /* i2s_u/ldata[14]/opit_0_inv/FFCD/FF */ #(
            .GRS_EN("TRUE"), 
            .SET_RESET("RESET"), 
            .LRS_EN("TRUE"), 
            .INIT(1'b0))
        \CLMS_102_129/FFCD/FF  (
            .Q (mic_data[14]),
            .CE (\CLMS_102_129/ntCECO ),
            .CK (ntclkbufg_0),
            .D (\i2s_u/shift_reg_l [14] ),
            .SR (\CLMS_102_129/ntRSCO ));
	// ../source/i2s_top.v:114

    V_LUT5CARRY /* dac_u/N9.lt_4/gateop_A2/FYA/V_FYS */ #(
            .INIT(32'b11011111000011011001000000001001), 
            .ID_TO_LUT("FALSE"), 
            .CIN_TO_LUT("FALSE"), 
            .I4_TO_CARRY("FALSE"), 
            .I4_TO_LUT("FALSE"))
        \CLMS_102_129/FYA/V_FYS  (
            .COUT (\CLMS_102_129/ntCYA ),
            .S (),
            .CIN (\dac_u/N9.co [6] ),
            .I0 (\dac_u/count [8] ),
            .I1 (N13[8]),
            .I2 (\dac_u/count [9] ),
            .I3 (N13[9]),
            .I4 (1'b0),
            .ID (1'b0));
	// LUT = (~I2&I3)|(I1&I3)|(~I0&I3)|(I1&~I2)|(~I0&~I2) ;
	// CARRY = ((~I0&~I1&~I2&~I3)|(I0&I1&~I2&~I3)|(~I0&~I1&I2&I3)|(I0&I1&I2&I3)) ? CIN : ((~I2&I3)|(I1&I3)|(~I0&I3)|(I1&~I2)|(~I0&~I2)) ;
	// ../source/dac_out.v:20

    V_LUT5CARRY /* dac_u/N9.lt_4/gateop_A2/FYB/V_FYSC */ #(
            .INIT(32'b11011111000011011001000000001001), 
            .ID_TO_LUT("FALSE"), 
            .CIN_TO_LUT("FALSE"), 
            .I4_TO_CARRY("FALSE"), 
            .I4_TO_LUT("FALSE"))
        \CLMS_102_129/FYB/V_FYSC  (
            .COUT (_N0),
            .S (),
            .CIN (\CLMS_102_129/ntCYA ),
            .I0 (\dac_u/count [10] ),
            .I1 (N13[10]),
            .I2 (\dac_u/count [11] ),
            .I3 (N13[11]),
            .I4 (1'b0),
            .ID (1'b0));
	// LUT = (~I2&I3)|(I1&I3)|(~I0&I3)|(I1&~I2)|(~I0&~I2) ;
	// CARRY = ((~I0&~I1&~I2&~I3)|(I0&I1&~I2&~I3)|(~I0&~I1&I2&I3)|(I0&I1&I2&I3)) ? CIN : ((~I2&I3)|(I1&I3)|(~I0&I3)|(I1&~I2)|(~I0&~I2)) ;
	// ../source/dac_out.v:20

    V_INV \CLMS_102_129/LRSPOLMUX/V_INV  (
            .Z (\CLMS_102_129/ntRS_P ),
            .I (nt_rst_n));
	// ../source/i2s_top.v:114

    V_BUF \CLMS_102_129/RSMUX/V_BUF  (
            .Z (\CLMS_102_129/ntRSCO ),
            .I (\CLMS_102_129/ntRS_P ));
	// ../source/i2s_top.v:114

    V_BUF \CLMS_102_137/CEMUX/V_BUF  (
            .Z (\CLMS_102_137/ntCECO ),
            .I (\i2s_u/N342 ));
	// ../source/i2s_top.v:52

    V_FFASYN /* i2s_u/shift_reg_l[23]/opit_0_inv/FF0/FF */ #(
            .GRS_EN("TRUE"), 
            .SET_RESET("RESET"), 
            .LRS_EN("TRUE"), 
            .INIT(1'b0))
        \CLMS_102_137/FF0/FF  (
            .Q (\i2s_u/shift_reg_l [23] ),
            .CE (\CLMS_102_137/ntCECO ),
            .CK (ntclkbufg_0),
            .D (\i2s_u/shift_reg_l [22] ),
            .SR (\CLMS_102_137/ntRSCO ));
	// ../source/i2s_top.v:52

    V_FFASYN /* i2s_u/shift_reg_l[22]/opit_0_inv/FF1/FF */ #(
            .GRS_EN("TRUE"), 
            .SET_RESET("RESET"), 
            .LRS_EN("TRUE"), 
            .INIT(1'b0))
        \CLMS_102_137/FF1/FF  (
            .Q (\i2s_u/shift_reg_l [22] ),
            .CE (\CLMS_102_137/ntCECO ),
            .CK (ntclkbufg_0),
            .D (\i2s_u/shift_reg_l [21] ),
            .SR (\CLMS_102_137/ntRSCO ));
	// ../source/i2s_top.v:52

    V_FFASYN /* i2s_u/shift_reg_l[21]/opit_0_inv/FF2/FF */ #(
            .GRS_EN("TRUE"), 
            .SET_RESET("RESET"), 
            .LRS_EN("TRUE"), 
            .INIT(1'b0))
        \CLMS_102_137/FF2/FF  (
            .Q (\i2s_u/shift_reg_l [21] ),
            .CE (\CLMS_102_137/ntCECO ),
            .CK (ntclkbufg_0),
            .D (\i2s_u/shift_reg_l [20] ),
            .SR (\CLMS_102_137/ntRSCO ));
	// ../source/i2s_top.v:52

    V_FFASYN /* i2s_u/shift_reg_l[19]/opit_0_inv/FF3/FF */ #(
            .GRS_EN("TRUE"), 
            .SET_RESET("RESET"), 
            .LRS_EN("TRUE"), 
            .INIT(1'b0))
        \CLMS_102_137/FF3/FF  (
            .Q (\i2s_u/shift_reg_l [19] ),
            .CE (\CLMS_102_137/ntCECO ),
            .CK (ntclkbufg_0),
            .D (\i2s_u/shift_reg_l [18] ),
            .SR (\CLMS_102_137/ntRSCO ));
	// ../source/i2s_top.v:52

    V_FFASYN /* i2s_u/shift_reg_l[2]/opit_0_inv/FFAB/FF */ #(
            .GRS_EN("TRUE"), 
            .SET_RESET("RESET"), 
            .LRS_EN("TRUE"), 
            .INIT(1'b0))
        \CLMS_102_137/FFAB/FF  (
            .Q (\i2s_u/shift_reg_l [2] ),
            .CE (\CLMS_102_137/ntCECO ),
            .CK (ntclkbufg_0),
            .D (\i2s_u/shift_reg_l [1] ),
            .SR (\CLMS_102_137/ntRSCO ));
	// ../source/i2s_top.v:52

    V_FFASYN /* i2s_u/shift_reg_l[3]/opit_0_inv/FFCD/FF */ #(
            .GRS_EN("TRUE"), 
            .SET_RESET("RESET"), 
            .LRS_EN("TRUE"), 
            .INIT(1'b0))
        \CLMS_102_137/FFCD/FF  (
            .Q (\i2s_u/shift_reg_l [3] ),
            .CE (\CLMS_102_137/ntCECO ),
            .CK (ntclkbufg_0),
            .D (\i2s_u/shift_reg_l [2] ),
            .SR (\CLMS_102_137/ntRSCO ));
	// ../source/i2s_top.v:52

    V_INV \CLMS_102_137/LRSPOLMUX/V_INV  (
            .Z (\CLMS_102_137/ntRS_P ),
            .I (nt_rst_n));
	// ../source/i2s_top.v:52

    V_BUF \CLMS_102_137/RSMUX/V_BUF  (
            .Z (\CLMS_102_137/ntRSCO ),
            .I (\CLMS_102_137/ntRS_P ));
	// ../source/i2s_top.v:52

    V_LUT5 /* i2s_u/N2_mux4/gateop_perm/FYA/FYS */ #(
            .INIT(32'b11101110101010101010101010101010))
        \CLMS_114_101/FYA/FYS  (
            .Y (nt_mic_sck),
            .I0 (\i2s_u/sck_cnt [4] ),
            .I1 (\i2s_u/sck_cnt [3] ),
            .I2 (1'b0),
            .I3 (\i2s_u/sck_cnt [2] ),
            .I4 (\i2s_u/sck_cnt [1] ));
	// LUT = (I1&I3&I4)|(I0) ;

    V_BUF \CLMS_114_109/CEMUX/V_BUF  (
            .Z (\CLMS_114_109/ntCECO ),
            .I (1'b1));
	// ../source/i2s_top.v:24

    V_FFASYN /* i2s_u/sck_cnt[2]/opit_0_inv_L5Q_perm/FF0/FF */ #(
            .GRS_EN("TRUE"), 
            .SET_RESET("RESET"), 
            .LRS_EN("TRUE"), 
            .INIT(1'b0))
        \CLMS_114_109/FF0/FF  (
            .Q (\i2s_u/sck_cnt [2] ),
            .CE (\CLMS_114_109/ntCECO ),
            .CK (ntclkbufg_0),
            .D (\CLMS_114_109/ntY0 ),
            .SR (\CLMS_114_109/ntRSCO ));
	// ../source/i2s_top.v:24

    V_FFASYN /* i2s_u/sck_cnt[3]/opit_0_inv_L5Q_perm/FF1/FF */ #(
            .GRS_EN("TRUE"), 
            .SET_RESET("RESET"), 
            .LRS_EN("TRUE"), 
            .INIT(1'b0))
        \CLMS_114_109/FF1/FF  (
            .Q (\i2s_u/sck_cnt [3] ),
            .CE (\CLMS_114_109/ntCECO ),
            .CK (ntclkbufg_0),
            .D (\CLMS_114_109/ntY1 ),
            .SR (\CLMS_114_109/ntRSCO ));
	// ../source/i2s_top.v:24

    V_FFASYN /* i2s_u/sck_cnt[4]/opit_0_inv_L5Q_perm/FF2/FF */ #(
            .GRS_EN("TRUE"), 
            .SET_RESET("RESET"), 
            .LRS_EN("TRUE"), 
            .INIT(1'b0))
        \CLMS_114_109/FF2/FF  (
            .Q (\i2s_u/sck_cnt [4] ),
            .CE (\CLMS_114_109/ntCECO ),
            .CK (ntclkbufg_0),
            .D (\CLMS_114_109/ntY2 ),
            .SR (\CLMS_114_109/ntRSCO ));
	// ../source/i2s_top.v:24

    V_FFASYN /* i2s_u/sck_cnt[1]/opit_0_inv_L5Q_perm/FF3/FF */ #(
            .GRS_EN("TRUE"), 
            .SET_RESET("RESET"), 
            .LRS_EN("TRUE"), 
            .INIT(1'b0))
        \CLMS_114_109/FF3/FF  (
            .Q (\i2s_u/sck_cnt [1] ),
            .CE (\CLMS_114_109/ntCECO ),
            .CK (ntclkbufg_0),
            .D (\CLMS_114_109/ntY3 ),
            .SR (\CLMS_114_109/ntRSCO ));
	// ../source/i2s_top.v:24

    V_LUT5 /* i2s_u/sck_cnt[2]/opit_0_inv_L5Q_perm/FYA/FYS */ #(
            .INIT(32'b01000110011001101100110011001100))
        \CLMS_114_109/FYA/FYS  (
            .Y (\CLMS_114_109/ntY0 ),
            .I0 (\i2s_u/sck_cnt [1] ),
            .I1 (\i2s_u/sck_cnt [2] ),
            .I2 (\i2s_u/sck_cnt [4] ),
            .I3 (\i2s_u/sck_cnt [3] ),
            .I4 (\i2s_u/sck_cnt [0] ));
	// LUT = (I1&~I4)|(I0&~I1&~I3&I4)|(I0&~I1&~I2&I4)|(~I0&I1) ;
	// ../source/i2s_top.v:24

    V_LUT5 /* i2s_u/sck_cnt[3]/opit_0_inv_L5Q_perm/FYB/FYSC */ #(
            .INIT(32'b01010111100010001111111100000000))
        \CLMS_114_109/FYB/FYSC  (
            .Y (\CLMS_114_109/ntY1 ),
            .I0 (\i2s_u/sck_cnt [1] ),
            .I1 (\i2s_u/sck_cnt [2] ),
            .I2 (\i2s_u/sck_cnt [4] ),
            .I3 (\i2s_u/sck_cnt [3] ),
            .I4 (\i2s_u/sck_cnt [0] ));
	// LUT = (I3&~I4)|(I0&I1&~I3&I4)|(~I1&~I2&I3)|(~I0&I3) ;
	// ../source/i2s_top.v:24

    V_LUT5 /* i2s_u/sck_cnt[4]/opit_0_inv_L5Q_perm/FYC/FYS */ #(
            .INIT(32'b01011000111100001111000011110000))
        \CLMS_114_109/FYC/FYS  (
            .Y (\CLMS_114_109/ntY2 ),
            .I0 (\i2s_u/sck_cnt [1] ),
            .I1 (\i2s_u/sck_cnt [2] ),
            .I2 (\i2s_u/sck_cnt [4] ),
            .I3 (\i2s_u/sck_cnt [3] ),
            .I4 (\i2s_u/sck_cnt [0] ));
	// LUT = (I2&~I4)|(I0&I1&~I2&I3&I4)|(I2&~I3)|(~I0&I2) ;
	// ../source/i2s_top.v:24

    V_LUT5 /* i2s_u/sck_cnt[1]/opit_0_inv_L5Q_perm/FYD/FYSC */ #(
            .INIT(32'b01010101010101011010101010101010))
        \CLMS_114_109/FYD/FYSC  (
            .Y (\CLMS_114_109/ntY3 ),
            .I0 (\i2s_u/sck_cnt [1] ),
            .I1 (1'b0),
            .I2 (1'b0),
            .I3 (1'b0),
            .I4 (\i2s_u/sck_cnt [0] ));
	// LUT = I4^I0 ;
	// ../source/i2s_top.v:24

    V_INV \CLMS_114_109/LRSPOLMUX/V_INV  (
            .Z (\CLMS_114_109/ntRS_P ),
            .I (nt_rst_n));
	// ../source/i2s_top.v:24

    V_BUF \CLMS_114_109/RSMUX/V_BUF  (
            .Z (\CLMS_114_109/ntRSCO ),
            .I (\CLMS_114_109/ntRS_P ));
	// ../source/i2s_top.v:24

    V_GRS GRS_INST (
            .GRS_N (1'b1));

    V_IBUF /* clk50M_ibuf/opit_0/ibuf */ #(
            .IOSTANDARD("LVCMOS12"), 
            .TERM_DDR("ON"))
        \IOBD_0_298/ibuf  (
            .O (\clk50M_ibuf/ntD ),
            .I (clk50M));
	// ../source/top.v:2

    V_OBUF /* mic_sck_obuf/opit_0/obuf */ #(
            .IOSTANDARD("LVCMOS33"), 
            .SLEW_RATE("SLOW"), 
            .DRIVE_STRENGTH("8"))
        \IOBD_152_86/obuf  (
            .O (mic_sck),
            .I (\mic_sck_obuf/ntO ));
	// ../source/top.v:5

    V_IBUF /* mic_sd_ibuf/opit_0/ibuf */ #(
            .IOSTANDARD("LVCMOS12"), 
            .TERM_DDR("ON"))
        \IOBD_152_90/ibuf  (
            .O (\mic_sd_ibuf/ntD ),
            .I (mic_sd));
	// ../source/top.v:7

    V_IBUF /* rst_n_ibuf/opit_0/ibuf */ #(
            .IOSTANDARD("LVCMOS12"), 
            .TERM_DDR("ON"))
        \IOBD_152_106/ibuf  (
            .O (\rst_n_ibuf/ntD ),
            .I (rst_n));
	// ../source/top.v:3

    V_OBUF /* mic_out_obuf/opit_0/obuf */ #(
            .IOSTANDARD("LVCMOS33"), 
            .SLEW_RATE("SLOW"), 
            .DRIVE_STRENGTH("8"))
        \IOBD_152_114/obuf  (
            .O (mic_out),
            .I (\mic_out_obuf/ntO ));
	// ../source/top.v:9

    V_OBUF /* mic_ws_obuf/opit_0/obuf */ #(
            .IOSTANDARD("LVCMOS33"), 
            .SLEW_RATE("SLOW"), 
            .DRIVE_STRENGTH("8"))
        \IOBS_152_9/obuf  (
            .O (mic_ws),
            .I (\mic_ws_obuf/ntO ));
	// ../source/top.v:6

    V_BUF \IOL_7_298/ntDI  (
            .Z (_N1),
            .I (\clk50M_ibuf/ntD ));
	// ../source/top.v:2

    V_MUX2 \IOL_151_9/MIPI_OUT/V_MUX2  (
            .Z (\IOL_151_9/MIPI_OUT/_N3 ),
            .I0 (\IOL_151_9/MIPI_OUT/_N1 ),
            .I1 (1'b0),
            .SEL (1'b0));
	// ../source/top.v:6

    V_BUF \IOL_151_9/OUTPUT_DATA_MUX/V_BUF  (
            .Z (\IOL_151_9/MIPI_OUT/_N1 ),
            .I (nt_mic_ws));
	// ../source/top.v:6

    V_BUF \IOL_151_9/OUT_DELSEL_MUX/V_BUF  (
            .Z (\mic_ws_obuf/ntO ),
            .I (\IOL_151_9/MIPI_OUT/_N3 ));
	// ../source/top.v:6

    V_MUX2 \IOL_151_86/MIPI_OUT/V_MUX2  (
            .Z (\IOL_151_86/MIPI_OUT/_N3 ),
            .I0 (\IOL_151_86/MIPI_OUT/_N1 ),
            .I1 (1'b0),
            .SEL (1'b0));
	// ../source/top.v:5

    V_BUF \IOL_151_86/OUTPUT_DATA_MUX/V_BUF  (
            .Z (\IOL_151_86/MIPI_OUT/_N1 ),
            .I (nt_mic_sck));
	// ../source/top.v:5

    V_BUF \IOL_151_86/OUT_DELSEL_MUX/V_BUF  (
            .Z (\mic_sck_obuf/ntO ),
            .I (\IOL_151_86/MIPI_OUT/_N3 ));
	// ../source/top.v:5

    V_BUF \IOL_151_90/IN_DELSEL_MUX/V_BUF  (
            .Z (nt_mic_sd),
            .I (\mic_sd_ibuf/ntD ));
	// ../source/top.v:7

    V_BUF \IOL_151_106/IN_DELSEL_MUX/V_BUF  (
            .Z (nt_rst_n),
            .I (\rst_n_ibuf/ntD ));
	// ../source/top.v:3

    V_MUX2 \IOL_151_114/MIPI_OUT/V_MUX2  (
            .Z (\IOL_151_114/MIPI_OUT/_N3 ),
            .I0 (\IOL_151_114/MIPI_OUT/_N1 ),
            .I1 (1'b0),
            .SEL (1'b0));
	// ../source/top.v:9

    V_BUF \IOL_151_114/OUTPUT_DATA_MUX/V_BUF  (
            .Z (\IOL_151_114/MIPI_OUT/_N1 ),
            .I (_N0));
	// ../source/top.v:9

    V_BUF \IOL_151_114/OUT_DELSEL_MUX/V_BUF  (
            .Z (\mic_out_obuf/ntO ),
            .I (\IOL_151_114/MIPI_OUT/_N3 ));
	// ../source/top.v:9

    V_PLL_E1 /* dac_pll_u/u_pll_e1/goppll/V_PLL_E1 */ #(
            .CLKIN_FREQ(50), 
            .PFDEN_EN("FALSE"), 
            .VCOCLK_DIV2(1'b0), 
            .DYNAMIC_RATIOI_EN("FALSE"), 
            .DYNAMIC_RATIO0_EN("FALSE"), 
            .DYNAMIC_RATIO1_EN("FALSE"), 
            .DYNAMIC_RATIO2_EN("FALSE"), 
            .DYNAMIC_RATIO3_EN("FALSE"), 
            .DYNAMIC_RATIO4_EN("FALSE"), 
            .DYNAMIC_RATIOF_EN("FALSE"), 
            .STATIC_RATIOI(2), 
            .STATIC_RATIO0(3), 
            .STATIC_RATIO1(16), 
            .STATIC_RATIO2(16), 
            .STATIC_RATIO3(16), 
            .STATIC_RATIO4(16), 
            .STATIC_RATIOF(24), 
            .DYNAMIC_DUTY0_EN("FALSE"), 
            .DYNAMIC_DUTY1_EN("FALSE"), 
            .DYNAMIC_DUTY2_EN("FALSE"), 
            .DYNAMIC_DUTY3_EN("FALSE"), 
            .DYNAMIC_DUTY4_EN("FALSE"), 
            .DYNAMIC_DUTYF_EN("FALSE"), 
            .STATIC_DUTY0(3), 
            .STATIC_DUTY1(16), 
            .STATIC_DUTY2(16), 
            .STATIC_DUTY3(16), 
            .STATIC_DUTY4(16), 
            .STATIC_DUTYF(24), 
            .PHASE_ADJUST0_EN("TRUE"), 
            .PHASE_ADJUST1_EN("TRUE"), 
            .PHASE_ADJUST2_EN("TRUE"), 
            .PHASE_ADJUST3_EN("TRUE"), 
            .PHASE_ADJUST4_EN("TRUE"), 
            .DYNAMIC_PHASE0_EN("FALSE"), 
            .DYNAMIC_PHASE1_EN("FALSE"), 
            .DYNAMIC_PHASE2_EN("FALSE"), 
            .DYNAMIC_PHASE3_EN("FALSE"), 
            .DYNAMIC_PHASE4_EN("FALSE"), 
            .DYNAMIC_PHASEF_EN("FALSE"), 
            .STATIC_PHASE0(0), 
            .STATIC_PHASE1(0), 
            .STATIC_PHASE2(0), 
            .STATIC_PHASE3(0), 
            .STATIC_PHASE4(0), 
            .STATIC_PHASEF(0), 
            .STATIC_CPHASE0(2), 
            .STATIC_CPHASE1(2), 
            .STATIC_CPHASE2(2), 
            .STATIC_CPHASE3(2), 
            .STATIC_CPHASE4(2), 
            .STATIC_CPHASEF(2), 
            .CLK_CAS0_EN("FALSE"), 
            .CLK_CAS1_EN("FALSE"), 
            .CLK_CAS2_EN("FALSE"), 
            .CLK_CAS3_EN("FALSE"), 
            .CLK_CAS4_EN("FALSE"), 
            .CLKOUT5_SEL(0), 
            .CLKIN_BYPASS_EN("FALSE"), 
            .CLKOUT0_SYN_EN("FALSE"), 
            .CLKOUT0_EXT_SYN_EN("FALSE"), 
            .CLKOUT1_SYN_EN("FALSE"), 
            .CLKOUT2_SYN_EN("FALSE"), 
            .CLKOUT3_SYN_EN("FALSE"), 
            .CLKOUT4_SYN_EN("FALSE"), 
            .CLKOUT5_SYN_EN("FALSE"), 
            .INTERNAL_FB("ENABLE"), 
            .EXTERNAL_FB("DISABLE"), 
            .BANDWIDTH("OPTIMIZED"), 
            .RSTODIV_PHASE_EN("FALSE"), 
            .SIM_DEVICE("PGL22G"))
        \PLL_82_319/V_PLL_E1  (
            .CPHASE0 ({ntR11, ntR11, ntR11, ntR11, ntR11, ntR11, ntR11, ntR11, ntR11, ntR11}),
            .CPHASE1 ({ntR11, ntR11, ntR11, ntR11, ntR11, ntR11, ntR11, ntR11, ntR11, ntR11}),
            .CPHASE2 ({ntR11, ntR11, ntR11, ntR11, ntR11, ntR11, ntR11, ntR11, ntR11, ntR11}),
            .CPHASE3 ({ntR11, ntR11, ntR11, ntR11, ntR11, ntR11, ntR11, ntR11, ntR11, ntR11}),
            .CPHASE4 ({ntR11, ntR11, ntR11, ntR11, ntR11, ntR11, ntR11, ntR11, ntR11, ntR11}),
            .CPHASEF ({1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0}),
            .DUTY0 ({ntR11, ntR11, ntR11, ntR11, ntR11, ntR11, ntR11, ntR11, ntR11, ntR11}),
            .DUTY1 ({ntR11, ntR11, ntR11, ntR11, ntR11, ntR11, ntR11, ntR11, ntR11, ntR11}),
            .DUTY2 ({ntR11, ntR11, ntR11, ntR11, ntR11, ntR11, ntR11, ntR11, ntR11, ntR11}),
            .DUTY3 ({ntR11, ntR11, ntR11, ntR11, ntR11, ntR11, ntR11, ntR11, ntR11, ntR11}),
            .DUTY4 ({ntR11, ntR11, ntR11, ntR11, ntR11, ntR11, ntR11, ntR11, ntR11, ntR11}),
            .DUTYF ({1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0, 1'b0}),
            .PHASE0 ({ntR11, ntR11, ntR11}),
            .PHASE1 ({ntR11, ntR11, ntR11}),
            .PHASE2 ({ntR11, ntR11, ntR11}),
            .PHASE3 ({ntR11, ntR11, ntR11}),
            .PHASE4 ({ntR11, ntR11, ntR11}),
            .PHASEF ({1'b0, 1'b0, 1'b0}),
            .RATIO0 ({ntR11, ntR11, ntR11, ntR11, ntR11, ntR11, ntR11, ntR11, ntR11, ntR11}),
            .RATIO1 ({ntR11, ntR11, ntR11, ntR11, ntR11, ntR11, ntR11, ntR11, ntR11, ntR11}),
            .RATIO2 ({ntR11, ntR11, ntR11, ntR11, ntR11, ntR11, ntR11, ntR11, ntR11, ntR11}),
            .RATIO3 ({ntR11, ntR11, ntR11, ntR11, ntR11, ntR11, ntR11, ntR11, ntR11, ntR11}),
            .RATIO4 ({ntR11, ntR11, ntR11, ntR11, ntR11, ntR11, ntR11, ntR11, ntR11, ntR11}),
            .RATIOF ({ntR11, ntR11, ntR11, ntR11, ntR11, ntR11, ntR11, ntR11, ntR11, ntR11}),
            .RATIOI ({ntR11, ntR11, ntR11, ntR11, ntR11, ntR11, ntR11, ntR11, ntR11, ntR11}),
            .CLKOUT0 (clk200M),
            .CLKOUT0_EXT (),
            .CLKOUT1 (),
            .CLKOUT2 (),
            .CLKOUT3 (),
            .CLKOUT4 (),
            .CLKOUT5 (),
            .CLKSWITCH_FLAG (),
            .LOCK (),
            .CLKFB (1'b0),
            .CLKIN1 (_N1),
            .CLKIN2 (ntR11),
            .CLKIN_SEL (ntR11),
            .CLKIN_SEL_EN (ntR11),
            .CLKOUT0_EXT_SYN (ntR11),
            .CLKOUT0_SYN (ntR11),
            .CLKOUT1_SYN (ntR11),
            .CLKOUT2_SYN (ntR11),
            .CLKOUT3_SYN (ntR11),
            .CLKOUT4_SYN (ntR11),
            .CLKOUT5_SYN (ntR11),
            .PFDEN (ntR11),
            .PLL_PWD (1'b0),
            .RST (ntR11),
            .RSTODIV_PHASE (ntR11));
	// ../ipcore/dac_pll/dac_pll.v:241

    V_USCM /* clkbufg_0/gopclkbufg/V_USCM */ #(
            .USCM_MODE("BUF_A"), 
            .SIM_DEVICE("LOGOS"))
        \USCM_74_104/V_USCM  (
            .CLKOUT (ntclkbufg_0),
            .CLK0 (_N1),
            .CLK1 (1'b0),
            .SEL (1'b0));
	// ../source/top.v:2

    V_USCM /* clkbufg_1/gopclkbufg/V_USCM */ #(
            .USCM_MODE("BUF_A"), 
            .SIM_DEVICE("LOGOS"))
        \USCM_74_105/V_USCM  (
            .CLKOUT (ntclkbufg_1),
            .CLK0 (clk200M),
            .CLK1 (1'b0),
            .SEL (1'b0));
	// ../ipcore/dac_pll/dac_pll.v:241


endmodule

